---
AWSTemplateFormatVersion: '2010-09-09'
Description: Test stack for network load-balancer
Outputs:
  AlwaysOKAlarmName:
    Description: AlwaysOKAlarm Name
    Value: !Ref AlwaysOKAlarm
  AlwaysFAILAlarmName:
    Description: AlwaysFAILAlarm Name
    Value: !Ref AlwaysFAILAlarm
  AlwaysINSUFFICIENTName:
    Description: AlwaysINSUFFICIENTAlarm Name
    Value: !Ref AlwaysINSUFFICIENTAlarm
Resources:
  AlwaysOKAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmDescription: "common:alarm:always_ok:2021-07-26"
      ActionsEnabled: false
      ComparisonOperator: "GreaterThanOrEqualToThreshold"
      EvaluationPeriods: 1
      MetricName: "AlwaysOK"
      Namespace: AWS/NetworkELB
      Period: 60
      Statistic: "Minimum"
      TreatMissingData: "notBreaching"
      Threshold: 100

  AlwaysFAILAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmDescription: "common:alarm:always_ok:2021-07-26"
      ActionsEnabled: false
      ComparisonOperator: "GreaterThanOrEqualToThreshold"
      EvaluationPeriods: 1
      MetricName: "AlwaysOK"
      Namespace: AWS/NetworkELB
      Period: 60
      Statistic: "Minimum"
      TreatMissingData: "breaching"
      Threshold: 100

  AlwaysINSUFFICIENTAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmDescription: "common:alarm:always_ok:2021-07-26"
      ActionsEnabled: false
      ComparisonOperator: "GreaterThanOrEqualToThreshold"
      EvaluationPeriods: 1
      MetricName: "AlwaysOK"
      Namespace: AWS/NetworkELB
      Period: 60
      Statistic: "Minimum"
      TreatMissingData: "missing"
      Threshold: 100
