AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SNSTopicARN:
    Type: String
Resources:
  ${AlarmLogicalId}:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmActions:
        - Ref: SNSTopicARN
      AlarmDescription: 'Alarm by Digito for Kinesis Data Analytics for Apache Flink/SQL applications that indicates if the number of Kinesis Processing Units currently in use, is exceeding specified ${Threshold} range'
      AlarmName: ${AlarmName}
      ComparisonOperator: LessThanLowerOrGreaterThanUpperThreshold
      EvaluationPeriods: ${EvaluationPeriods}
      DatapointsToAlarm: ${DatapointsToAlarm}
      Metrics:
        - Expression:
             'ANOMALY_DETECTION_BAND(m1,${Threshold})'
          Id: ad1
        - Id: m1
          MetricStat:
            Metric:
              MetricName: KPUs
              Namespace: AWS/KinesisAnalytics
              Dimensions:
                - Name: Application
                  Value: '${KinesisAnalyticsAppName}'
            Period: 300
            Stat: Average
      ThresholdMetricId: ad1
      TreatMissingData: notBreaching
