---
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SNSTopicARN:
    Type: String
Resources:
  ${AlarmLogicalId}:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmName: ${AlarmName}
      AlarmDescription: |
        Alarm by Digito that is triggered when ConnectionEstablishedCount is less than the value for
        ConnectionAttemptCount, this indicates that clients behind the NAT gateway attempted to establish
        new connections for which there was no response
      AlarmActions:
        - Ref: SNSTopicARN
      Metrics:
        - Id: m1
          MetricStat:
            Metric:
              MetricName: ConnectionAttemptCount
              Namespace: AWS/NATGateway
              Dimensions:
                - Name: NatGatewayId
                  Value: ${NatGatewayId}
            Period: 60
            Stat: Average
          ReturnData: False
        - Id: m2
          MetricStat:
            Metric:
              MetricName: ConnectionEstablishedCount
              Namespace: AWS/NATGateway
              Dimensions:
                - Name: NatGatewayId
                  Value: ${NatGatewayId}
            Period: 60
            Stat: Average
          ReturnData: False
        - Expression: m1 > m2
          Id: c1
      Threshold: 0
      EvaluationPeriods: 5
      DatapointsToAlarm: 3
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
