#!/bin/sh

start=$(date +%s)
echo "========== Started pre-push git hook at $(date -R) =========="
# Keep in mind that the current working directory for .git/hooks is the root of the project
(make -f common.mk unit_test metadata_validator)
exit_code=$?
end=$(date +%s)
echo "========== Finished pre-push git hook with error code $exit_code at $(date -R). The duration is $((end - start)) second(-s) =========="
exit $exit_code
