AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SNSTopicARN:
    Type: String
Resources:
  ${AlarmLogicalId}:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmActions:
        - Ref: SNSTopicARN
      AlarmDescription: 'Alarm by Digito that indicates when number of open connections is greater than ${Threshold}'
      AlarmName: ${AlarmName}
      ComparisonOperator: GreaterThanUpperThreshold
      EvaluationPeriods: 5
      DatapointsToAlarm: 3
      Metrics:
        - Expression:
             'ANOMALY_DETECTION_BAND(m1,${Threshold})'
          Id: ad1
        - Id: m1
          MetricStat:
            Metric:
              MetricName: DatabaseConnections
              Namespace: AWS/DocDB
              Dimensions:
                - Name: DBInstanceIdentifier
                  Value: '${DBInstancePrimaryIdentifier}'
            Period: 60
            Stat: Maximum
      ThresholdMetricId: ad1
      TreatMissingData: missing
