AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SNSTopicARN:
    Type: String
Resources:
  AbnormalRequestPerTargetAnomalyDetector:
    Type: 'AWS::CloudWatch::AnomalyDetector'
    Properties:
      MetricName: RequestCountPerTarget
      Namespace: AWS/ApplicationELB
      Stat: Average
  AbnormalRequestPerTargetAlarm:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmActions:
        - Ref: SNSTopicARN
      AlarmDescription:
        Fn::Join: [ '', [ 'Alarm by Digito that reports when target group request count is anomalous with band width ', ${Threshold} ] ]
      AlarmName: ${AlarmName}
      ComparisonOperator: GreaterThanUpperThreshold
      EvaluationPeriods: 15
      DatapointsToAlarm: 10
      Metrics:
        - Expression:
            Fn::Join: [ '', [ 'ANOMALY_DETECTION_BAND(m1,', ${Threshold}, ')' ] ]
          Id: ad1
        - Id: m1
          MetricStat:
            Metric:
              MetricName: RequestCountPerTarget
              Namespace: AWS/ApplicationELB
              Dimensions:
                - Name: TargetGroup
                  Value: ${TargetGroup}
            Period: 60
            Stat: Average
      ThresholdMetricId: ad1
      TreatMissingData: missing
