AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  InstanceId:
    Type: String
    Default: '${InstanceId}'
  SNSTopicARN:
    Type: String
  Threshold:
    Type: String
    Default: ${Threshold}
Resources:
  LowStorageAlarm:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmActions:
        - Ref: SNSTopicARN
      AlarmDescription:
        Fn::Join: [ '', [ 'Alarm by Digito that reports when disk usage is over ', Ref: Threshold, '%' ] ]
      AlarmName:
        Fn::Join: [ '', [ 'DigitoEc2LowStorage-', Ref: InstanceId ] ]
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 3
      DatapointsToAlarm: 3
      Dimensions:
        - Name: InstanceId
          Value:
            Ref: InstanceId
      MetricName: disk_used_percent
      Namespace: CWAgent
      Period: 60
      Statistic: Maximum
      Threshold:
        Ref: Threshold
      TreatMissingData: missing
    Metadata:
      'AWS::Digito::Alarm':
        recommendationId: compute:alarm:ec2-cloudwatch-used-disk:2020-07-13
