---
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SNSTopicARN:
    Type: String
Resources:
  ${AlarmLogicalId}:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmName: ${AlarmName}
      AlarmDescription: |
        When ApproximateAgeOfOldestMessage of a message in dead-letter queue gets close to the retention period
        a customer set when configuring that queue.
        If a message gets too old, it will be discarded from the dead-letter queue,
        and a customer will lose the recovery way by leveraging a DLQ mechanism.
      AlarmActions:
        - Ref: SNSTopicARN
      MetricName: ApproximateAgeOfOldestMessage
      Namespace: AWS/SQS
      Dimensions:
        - Name: QueueName
          Value: ${QueueName}
      Period: 60
      Statistic: Maximum
      Threshold: ${Threshold}
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
