version: 0.2

phases:
  install:
    #If you use the Ubuntu standard image 2.0 or later, you must specify runtime-versions.
    #If you specify runtime-versions and use an image other than Ubuntu standard image 2.0, the build fails.
    runtime-versions:
      python: latest
    commands:
      - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
      - python get-pip.py
      - python -m pip install -r requirements.txt
  build:
    commands:
      - python -m flake8
      - python -m pytest -m style_validator --no-cov
      - python -m cfnlint -a ${CODEBUILD_SRC_DIR}/cfn_lint/rules/assume_role_templates -t documents/**/AutomationAssumeRoleTemplate.yml
      - python -m cfnlint -a ${CODEBUILD_SRC_DIR}/cfn_lint/rules/alarm_templates -o ${CODEBUILD_SRC_DIR}/cfn_lint/specs/AlarmHasActionSpec.json -i E3006 E1029 E3012 E0000 E1019 -t documents/**/AlarmTemplate.yml
      - python -m cfnlint -a ${CODEBUILD_SRC_DIR}/cfn_lint/rules/resource_manager_templates -i W1020 -t resource_manager/cloud_formation_templates/*.yml resource_manager/cloud_formation_templates/**/*.yml
      - python -m pytest -m unit_test --junitxml=test-reports/junit_report.xml --timeout=50 --disable-socket --reruns 5
reports:
  pytest_reports:
    files:
     - junit_report.xml
    base-directory: test-reports
    file-format: JunitXml
