version: 0.2

phases:
  install:
    #If you use the Ubuntu standard image 2.0 or later, you must specify runtime-versions.
    #If you specify runtime-versions and use an image other than Ubuntu standard image 2.0, the build fails.
    runtime-versions:
      python: latest
    commands:
      - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
      - python get-pip.py
      - python -m pip install -r requirements.txt
      - pip install --upgrade awscli
      - aws --version
  build:
    commands:
      # Executing destroy resources with [EXECUTE_FAILED] state which are older than [720] minutes or [12] hours.
      - PYTHONPATH=. python3.8 resource_manager/src/tools/resource_tool.py -c DESTROY_ALL -s EXECUTE_FAILED -a 720