version: 0.2

phases:
  install:
    #If you use the Ubuntu standard image 2.0 or later, you must specify runtime-versions.
    #If you specify runtime-versions and use an image other than Ubuntu standard image 2.0, the build fails.
    runtime-versions:
      python: latest
    commands:
      - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
      - python get-pip.py
      - python -m pip install -r requirements.txt
      - pip install --upgrade awscli
      - aws --version
  build:
    commands:
      # TODO (semiond): Temporary solution to fix stalled resources before executing integration tests on different machines (sessions).
      # Permanent solution is to tie resource to specific session so that other session will not try to fix it while it is in use.
      # https://issues.amazon.com/issues/Digito-2017
      - python -m pytest -m fix_integ_test_stalled_resources --no-cov