AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SNSTopicARN:
    Type: String
Resources:
  ConnectionSpikeAnomalyDetector:
    Type: 'AWS::CloudWatch::AnomalyDetector'
    Properties:
      MetricName: DatabaseConnections
      Namespace: AWS/RDS
      Stat: Maximum
  ConnectionSpikeAlarm:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmActions:
        - Ref: SNSTopicARN
      AlarmDescription:
        Fn::Join: [ '', [ 'Alarm by Digito that reports when connections are anomalous with band width ', ${Threshold} ] ]
      AlarmName: ${AlarmName}
      ComparisonOperator: LessThanLowerOrGreaterThanUpperThreshold
      DatapointsToAlarm: 3
      EvaluationPeriods: 5
      Metrics:
        - Expression:
            Fn::Join: [ '', [ 'ANOMALY_DETECTION_BAND(m1,', ${Threshold}, ')' ] ]
          Id: ad1
        - Id: m1
          MetricStat:
            Metric:
              MetricName: DatabaseConnections
              Namespace: AWS/RDS
              Dimensions:
                - Name: DBInstanceIdentifier
                  Value:
                    '${DBInstanceIdentifier}'
            Period: 60
            Stat: Maximum
      ThresholdMetricId: ad1
      TreatMissingData: missing
