---
AWSTemplateFormatVersion: 2010-09-09
Parameters:
  SNSTopicARN:
    Type: String
Resources:
  ${AlarmLogicalId}:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmName: ${AlarmName}
      AlarmActions:
        - Ref: SNSTopicARN
      AlarmDescription: "Alarm by Digito for AWS Backup that indicates a restore jobs that AWS Backup attempted to perform but could not complete under the ${BackupVaultName} backup vault"
      ActionsEnabled: false
      MetricName: NumberOfRestoreJobsFailed
      Namespace: AWS/Backup
      Period: 60
      Statistic: Maximum
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      ComparisonOperator: GreaterThanThreshold
      Threshold: ${Threshold}
      Dimensions:
        - Name: BackupVaultName
          Value: ${BackupVaultName}
      TreatMissingData: notBreaching
...
