---
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SNSTopicARN:
    Type: String
Resources:
  ${AlarmLogicalId}:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmName: ${AlarmName}
      AlarmDescription:
        Fn::Sub: 'Alarm by Digito that reports when VolumeBytesUsed is over ${Threshold} bytes'
      AlarmActions:
        - Ref: SNSTopicARN
      MetricName: VolumeBytesUsed
      Namespace: AWS/DocDB
      Dimensions:
        - Name: DBClusterIdentifier
          Value: ${DBClusterIdentifier}
      Period: 300
      Statistic: Minimum
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Threshold: ${Threshold}
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: missing
