AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SNSTopicARN:
    Type: String
Resources:
  ${AlarmLogicalId}:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions:
        - Ref: SNSTopicARN
      AlarmDescription:
        Fn::Join: [ '', [ 'Alarm by Digito that is triggered when synthetic canary SuccessPercent drops below ', ${Threshold}, '%' ] ]
      AlarmName: ${AlarmName}
      ComparisonOperator: LessThanThreshold
      EvaluationPeriods: 3
      DatapointsToAlarm: 2
      Dimensions:
        - Name: CanaryName
          Value: ${CanaryName}
      MetricName: SuccessPercent
      Namespace: CloudWatchSynthetics
      Period: 60
      Statistic: Average
      Threshold: ${Threshold}
      TreatMissingData: missing
      Unit: Percent
