---
AWSTemplateFormatVersion: 2010-09-09
Parameters:
  SNSTopicARN:
    Type: String
Resources:
  ${AlarmLogicalId}:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmName: ${AlarmName}
      AlarmActions:
        - Ref: SNSTopicARN
      AlarmDescription: "backup:alarm:copy-jobs-aborted:2020-12-06"
      ActionsEnabled: false
      MetricName: NumberOfCopyJobsFailed
      Namespace: AWS/Backup
      Period: 60
      Statistic: Maximum
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      ComparisonOperator: GreaterThanThreshold
      Threshold: ${Threshold}
      Dimensions:
        - Name: BackupVaultName
          Value: ${BackupVaultName}
      TreatMissingData: notBreaching
...
