AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SNSTopicARN:
    Type: String
Resources:
  ${AlarmLogicalId}:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmActions:
        - Ref: SNSTopicARN
      AlarmDescription: 'Alarm by Digito that reports when database replica lag is over ${Threshold} seconds'
      AlarmName: ${AlarmName}
      ComparisonOperator: GreaterThanOrEqualToThreshold
      DatapointsToAlarm: 3
      Dimensions:
        - Name: DBInstanceIdentifier
          Value: '${DBInstanceIdentifier}'
      EvaluationPeriods: 5
      MetricName: AuroraReplicaLag
      Namespace: AWS/RDS
      Period: 60
      Statistic: Maximum
      Threshold: ${Threshold}
      TreatMissingData: missing
