AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  DBInstanceIdentifier:
    Type: String
    Default: '${DBInstanceIdentifier}'
  SNSTopicARN:
    Type: String
  Threshold:
    Type: Number
    Default: ${Threshold}
Resources:
  OverUtilizedCPUAlarm:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmActions:
        - Ref: SNSTopicARN
      AlarmDescription:
        Fn::Join: [ '', [ 'Alarm by Digito that reports when database replica lag is over ', Ref: Threshold, 'seconds' ] ]
      AlarmName:
        Fn::Join: [ '', [ 'DigitoRdsAuroraReplicaLag-', Ref: DBInstanceIdentifier ] ]
      ComparisonOperator: GreaterThanOrEqualToThreshold
      DatapointsToAlarm: 3
      Dimensions:
        - Name: DBInstanceIdentifier
          Value:
            Ref: DBInstanceIdentifier
      EvaluationPeriods: 5
      MetricName: AuroraReplicaLag
      Namespace: AWS/RDS
      Period: 60
      Statistic: Maximum
      Threshold:
        Ref: Threshold
      TreatMissingData: missing
