---
AWSTemplateFormatVersion: 2010-09-09
Parameters:
  SNSTopicARN:
    Type: String
Resources:
  ${AlarmLogicalId}:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmName: ${AlarmName}
      AlarmActions:
        - Ref: SNSTopicARN
      AlarmDescription: "The number of backup jobs that AWS Backup attempted to delete based on backup retention lifecycle, but could not delete under the ${BackupVaultName} backup vault"
      ActionsEnabled: false
      MetricName: NumberOfBackupJobsExpired
      Namespace: AWS/Backup
      Period: 60
      Statistic: Maximum
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      ComparisonOperator: GreaterThanThreshold
      Threshold: ${Threshold}
      Dimensions:
        - Name: BackupVaultName
          Value: ${BackupVaultName}
      TreatMissingData: notBreaching
...
