AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SNSTopicARN:
    Type: String
Resources:
  ${AlarmLogicalId}:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmActions:
        - Ref: SNSTopicARN
      AlarmDescription: 'Alarm by Digito that tracks abnormal backend response time'
      AlarmName: ${AlarmName}
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 5
      DatapointsToAlarm: 3
      Dimensions:
        - Name: ApiName
          Value: '${ApiName}'
      MetricName: IntegrationLatency
      Namespace: AWS/ApiGateway
      ExtendedStatistic: p90
      Period: 60
      Threshold: ${Threshold}
      TreatMissingData: missing
