AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SNSTopicARN:
    Type: String
Resources:
  ${AlarmLogicalId}:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmActions:
        - Ref: SNSTopicARN
      AlarmDescription:
        'Alarm by Digito that reports when over time an ASG has many unhealthy hosts'
      AlarmName: ${AlarmName}
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 180
      DatapointsToAlarm: 30
      Dimensions:
        - Name: LoadBalancerName
          Value: '${LoadBalancerName}'
      MetricName: UnHealthyHostCount
      Namespace: AWS/ELB
      Period: 60
      Statistic: Maximum
      Threshold: ${Threshold}
      TreatMissingData: missing
