AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SNSTopicARN:
    Type: String
Resources:
  ${AlarmLogicalId}:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmActions:
        - Ref: SNSTopicARN
      AlarmDescription: 'Digito alarm that tracks the 4xx responses received from S3'
      AlarmName: ${AlarmName}
      MetricName: 4xxErrors
      Namespace: AWS/S3
      Dimensions:
        - Name: BucketName
          Value: '${S3BucketName}'
        - Name: FilterId
          Value: "${S3BucketName}-metrics"
      Period: 60
      EvaluationPeriods: 3
      DatapointsToAlarm: 2
      ExtendedStatistic: p80
      Threshold: ${Threshold}
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: missing
      Unit: Count
