AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SNSTopicARN:
    Type: String
Resources:
  ${AlarmLogicalId}:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmActions:
        - Ref: SNSTopicARN
      AlarmDescription: 'Digito alarm that tracks the 4xx responses received from API-Gateway. Remember that some services may expect a certain percent of legitimate 4xx responses'
      AlarmName: ${AlarmName}
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 5
      DatapointsToAlarm: 3
      Dimensions:
        - Name: ApiName
          Value: '${ApiName}'
      MetricName: 4XXError
      Namespace: AWS/ApiGateway
      Period: 60
      ExtendedStatistic: p80
      Threshold: ${Threshold}
      TreatMissingData: missing
