#
# Copyright 2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this
# software and associated documentation files (the "Software"), to deal in the Software
# without restriction, including without limitation the rights to use, copy, modify,
# merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
# PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
---
AWSTemplateFormatVersion: 2010-09-09
Description: Role for SSM RestoreFromBackup
Outputs:
  DigitoRestoreFromBackupAssumeRole:
    Description: DigitoRestoreFromBackup Automation Assume Role ARN
    Value: !GetAtt DigitoRestoreFromBackupAssumeRole.Arn
Resources:
  DigitoRestoreFromBackupAssumeRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ssm.amazonaws.com
            Action:
              - sts:AssumeRole
  DigitoRestoreFromBackupAssumePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: DigitoRestoreFromBackupAssumePolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Resource: "*"
            Action:
              - s3:PutObject
              - s3:GetObject
              - s3:ListBucket
              - s3:ListObjectVersions
              - s3:ListBucketVersions
              - s3:DeleteObject
              - s3:DeleteObject*
      Roles:
        - Ref: DigitoRestoreFromBackupAssumeRole
