AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SNSTopicARN:
    Type: String
Resources:
  ${AlarmLogicalId}:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmActions:
        - Ref: SNSTopicARN
      AlarmDescription: 'Alarm by Digito that indicates when the amount of storage available to each instance for temporary tables and logs is less than or equal to ${Threshold}'
      AlarmName: ${AlarmName}
      ComparisonOperator: LessThanOrEqualToThreshold
      EvaluationPeriods: 5
      DatapointsToAlarm: 3
      Dimensions:
        - Name: DBClusterIdentifier
          Value: '${DBClusterIdentifier}'
      MetricName: FreeLocalStorage
      Namespace: AWS/DocDB
      Period: 60
      Statistic: Minimum
      Threshold: ${Threshold}
      TreatMissingData: missing
