AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SNSTopicARN:
    Type: String
Resources:
  ${AlarmLogicalId}:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmActions:
        - Ref: SNSTopicARN
      AlarmDescription: 'Alarm by Digito for Amazon Redshift that reports when cluster is unhealthy, and the cluster name is ${ClusterName}.'
      AlarmName: ${AlarmName}
      ComparisonOperator: LessThanThreshold
      DatapointsToAlarm: ${DatapointsToAlarm}
      EvaluationPeriods: ${EvaluationPeriods}
      MetricName: HealthStatus
      Namespace: AWS/Redshift
      Dimensions:
        - Name: ClusterIdentifier
          Value: '${ClusterName}'
      Period: 60
      Statistic: Minimum
      Threshold: ${Threshold}
      TreatMissingData: missing
