AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SNSTopicARN:
    Type: String
Resources:
  ${AlarmLogicalId}:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmActions:
        - Ref: SNSTopicARN
      AlarmDescription: 'Alarm by Digito Digito alarm that tracks abnormal response time.'
      AlarmName: ${AlarmName}
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 5
      DatapointsToAlarm: 3
      Dimensions:
        - Name: ApiName
          Value: '${ApiName}'
      MetricName: Latency
      Namespace: AWS/ApiGateway
      ExtendedStatistic: p90
      Period: 60
      Threshold: ${Threshold}
      TreatMissingData: missing
