AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SNSTopicARN:
    Type: String
Resources:
  ${AlarmLogicalId}:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmActions:
        - Ref: SNSTopicARN
      AlarmDescription: 'Alarm by Digito that reports when a followed process is reported stopped'
      AlarmName: ${AlarmName}
      ComparisonOperator: LessThanThreshold
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Dimensions:
        - Name: InstanceId
          Value: '${InstanceId}'
        - Name: pidfile
          Value:
            Ref: '${PidPath}'
        - Name: pid_finder
          Value: 'native'
      MetricName: procstat_lookup_pid_count
      Namespace: CWAgent
      Period: 60
      Statistic: Maximum
      Threshold: ${Threshold}
      TreatMissingData: missing
