AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  InstanceId:
    Type: String
    Default: '${InstanceId}'
  PidPath:
    Type: String
  SNSTopicARN:
    Type: String
  Threshold:
    Type: Number
    Default: ${Threshold}
Resources:
  DeadProcessAlarm:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmActions:
        - Ref: SNSTopicARN
      AlarmDescription:
        Fn::Join: [ '', [ 'Alarm by Digito that reports when a followed process is reported stopped' ] ]
      AlarmName:
        Fn::Join: [ '', [ 'DigitoEc2DeadProcess-', Ref: InstanceId ] ]
      ComparisonOperator: LessThanThreshold
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Dimensions:
        - Name: InstanceId
          Value:
            Ref: InstanceId
        - Name: pidfile
          Value:
            Ref: PidPath
        - Name: pid_finder
          Value: 'native'
      MetricName: procstat_lookup_pid_count
      Namespace: CWAgent
      Period: 60
      Statistic: Maximum
      Threshold:
        Ref: Threshold
      TreatMissingData: missing
    Metadata:
      'AWS::Digito::Monitoring':
        recommendationId: 'compute:alarm:ec2-procstate-pid-cnt:2020-07-13'
