AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SNSTopicARN:
    Type: String
  CanaryName:
    Type: String
Resources:
  ${AlarmLogicalId}:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions:
        - Ref: SNSTopicARN
      AlarmDescription: >
        A fallback monitor setup in an independent region to provide alerts in case of a whole region
        failure. It is triggered when synthetic canary SuccessPercent drops below ${Threshold}%'
      AlarmName: ${AlarmName}
      ComparisonOperator: LessThanThreshold
      EvaluationPeriods: 5
      DatapointsToAlarm: 5
      Dimensions:
        - Name: CanaryName
          Value:
            Ref: CanaryName
      MetricName: SuccessPercent
      Namespace: CloudWatchSynthetics
      Period: 60
      Statistic: Average
      Threshold: ${Threshold}
      TreatMissingData: missing
      Unit: Percent
