---
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SNSTopicARN:
    Type: String
Resources:
  ${AlarmLogicalId}:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmName: ${AlarmName}
      AlarmDescription: |
        A value greater than zero indicates that there are connections that have been moved to an idle state.
        If the value for IdleTimeoutCount increases, it may indicate that clients behind the NAT gateway are
        re-using stale connections
      AlarmActions:
        - Ref: SNSTopicARN
      MetricName: IdleTimeoutCount
      Namespace: AWS/NATGateway
      Dimensions:
        - Name: NatGatewayId
          Value: ${NatGatewayId}
      Period: 60
      Statistic: Average
      Threshold: ${Threshold}
      EvaluationPeriods: 5
      DatapointsToAlarm: 3
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
