AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SNSTopicARN:
    Type: String
Resources:
  ${AlarmLogicalId}:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmActions:
        - Ref: SNSTopicARN
      AlarmDescription: 'Alarm by Digito that indicates when the amount of swap space used on the instance is greater than or equal to ${Threshold}'
      AlarmName: ${AlarmName}
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 5
      DatapointsToAlarm: 3
      Dimensions:
        - Name: DBInstanceIdentifier
          Value: '${DBInstancePrimaryIdentifier}'
      MetricName: SwapUsage
      Namespace: AWS/DocDB
      Period: 60
      Statistic: Minimum
      Threshold: ${Threshold}
      TreatMissingData: missing
