---
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SNSTopicARN:
    Type: String
Resources:
  MountFailureMetric:
    Type: AWS::Logs::MetricFilter
    Properties:
      FilterPattern: "Mount failed"
      LogGroupName: ${LogGroupName}
      MetricTransformations:
        - MetricValue: "1"
          DefaultValue: 0.0
          MetricNamespace: "EFSMounts"
          MetricName: 'MountFailures'
  ${AlarmLogicalId}:
      Type: "AWS::CloudWatch::Alarm"
      Properties:
        AlarmName: ${AlarmName}
        AlarmDescription: This alarm triggers when EFS fails to mount to a filesystem
        AlarmActions:
          - Ref: SNSTopicARN
        MetricName: 'MountFailures'
        Namespace: EFSMounts
        Statistic: Maximum
        Period: 60
        EvaluationPeriods: 1
        DatapointsToAlarm: 1
        Threshold: ${Threshold}
        ComparisonOperator: GreaterThanThreshold
        TreatMissingData: notBreaching
        Unit: None
