AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SNSTopicARN:
    Type: String
Outputs:
  AlarmName:
    Type: String
    Description: Mount Failure Alarm Name
    Default: !Ref MountFailureAlarm
Resources:
  MountFailureAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmName: ${AlarmName}
      AlarmDescription: "efs:alarm:ec2-mount-failure:2020-04-01"
      ActionsEnabled: false
      MetricName: MountFailure
      Namespace: AWS/EFS
      Statistic: Maximum
      Dimensions:
        - Name: EFS
          Value: ${FileSystem}
      Period: 30
      EvaluationPeriods: 5
      DatapointsToAlarm: 1
      Threshold: 1
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: missing
      Unit: Count
