AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SNSTopicARN:
    Type: String
Resources:
  ${AlarmLogicalId}:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmActions:
        - Ref: SNSTopicARN
      AlarmDescription: 'Alarm by Digito for Elasticache that indicates when the total number of client connections registered by the Redis engine, exceeds specified ${Threshold} limit'
      AlarmName: ${AlarmName}
      EvaluationPeriods: 5
      DatapointsToAlarm: 2
      ComparisonOperator: LessThanLowerOrGreaterThanUpperThreshold
      Metrics:
        - Expression:
            'ANOMALY_DETECTION_BAND(m1,${Threshold})'
          Id: ad1
        - Id: m1
          MetricStat:
            Metric:
              MetricName: CurrConnections
              Namespace: AWS/ElastiCache
              Dimensions:
                - Name: CacheClusterId
                  Value: '${ClusterId}'
            Period: 60
            Stat: Maximum
      ThresholdMetricId: ad1
      TreatMissingData: missing