---
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SNSTopicARN:
    Type: String
Resources:
  ${AlarmLogicalId}:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmName: ${AlarmName}
      AlarmDescription: |
        Alarm by Digito that triggers if SentMessageSize became close to allowed Threshold in bytes.
        It needs to investigate the current characteristics of input data and even change the code
        to move data by another way
      ActionsEnabled: false
      AlarmActions:
        - Ref: SNSTopicARN
      MetricName: SentMessageSize
      Namespace: AWS/SQS
      Dimensions:
        - Name: QueueName
          Value: ${QueueName}
      Period: 60
      Statistic: Average
      Threshold: ${Threshold}
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: missing
