AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SNSTopicARN:
    Type: String
Resources:
  ${AlarmLogicalId}:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmActions:
        - Ref: SNSTopicARN
      AlarmDescription: 'Alarm by Digito that reports when memory limit is exceeded with ${Threshold}'
      AlarmName: ${AlarmName}
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Dimensions:
        - Name: function_name
          Value: '${FunctionName}'
      MetricName: used_memory_max
      Namespace: LambdaInsights
      Period: 180
      Statistic: Maximum
      Threshold: ${Threshold}
      TreatMissingData: missing
