---
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SNSTopicARN:
    Type: String
Resources:
  ${AlarmLogicalId}:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmName: ${AlarmName}
      AlarmDescription:
        Fn::Sub: 'Alarm by Digito that reports when DiskQueueDepth is higher or equal to ${Threshold}'
      AlarmActions:
        - Ref: SNSTopicARN
      MetricName: DiskQueueDepth
      Namespace: AWS/DocDB
      Dimensions:
        - Name: DBInstanceIdentifier
          Value: ${DBInstanceIdentifier}
      Period: 60
      Statistic: Maximum
      Threshold: ${Threshold}
      EvaluationPeriods: 5
      DatapointsToAlarm: 3
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: missing
