AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SNSTopicARN:
    Type: String
Resources:
  ${AlarmLogicalId}:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmActions:
        - Ref: SNSTopicARN
      AlarmDescription: 'Alarm by Digito for Amazon Elasticache for Redis that indicates when the total number of failed attempts to authenticate with the Redis AUTH command is exceeding specified ${Threshold} limit'
      AlarmName: ${AlarmName}
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 5
      DatapointsToAlarm: 1
      Dimensions:
        - Name: CacheClusterId
          Value: '${ClusterId}'
      MetricName: AuthenticationFailures
      Namespace: AWS/ElastiCache
      Period: 60
      Statistic: Maximum
      Threshold: ${Threshold}
      TreatMissingData: missing
