AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SNSTopicARN:
    Type: String
Resources:
  ${AlarmLogicalId}:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmActions:
        - Ref: SNSTopicARN
      AlarmDescription: 'Alarm by Digito for Kinesis Data Analytics for SQL applications that indicates the total number of records returned by a Lambda function that were marked with Dropped status, is exceeding specified ${Threshold} limit'
      AlarmName: ${AlarmName}
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: ${EvaluationPeriods}
      DatapointsToAlarm: ${DatapointsToAlarm}
      Dimensions:
        - Name: Application
          Value: '${KinesisAnalyticsAppName}'
        - Name: Id
          Value: '${KinesisAnalyticsInputId}'
        - Name: Flow
          Value: Input
      Namespace: AWS/KinesisAnalytics
      MetricName: InputProcessing.DroppedRecords
      Period: 60
      Statistic: Maximum
      Threshold: ${Threshold}
      TreatMissingData: missing
