AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SNSTopicARN:
    Type: String
Resources:
  ${AlarmLogicalId}:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmActions:
        - Ref: SNSTopicARN
      AlarmDescription: 'Alarm by Digito that reports when volume read throughput is anomalous with band width ${BandWidth}'
      AlarmName: ${AlarmName}
      ComparisonOperator: LessThanLowerOrGreaterThanUpperThreshold
      DatapointsToAlarm: 3
      EvaluationPeriods: 3
      Metrics:
        - Expression:
            'ANOMALY_DETECTION_BAND(m1,${BandWidth})'
          Id: ad1
        - Id: m1
          MetricStat:
            Metric:
              MetricName: VolumeReadBytes
              Namespace: AWS/EBS
              Dimensions:
                - Name: VolumeId
                  Value: '${VolumeId}'
            Period: 300
            Stat: Sum
      ThresholdMetricId: ad1
      TreatMissingData: missing
    Metadata:
      'AWS::Digito::Monitoring':
        recommendationId: 'compute:alarm:ebs-read-throughput:2020-12-06'
