AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SNSTopicARN:
    Type: String
Resources:
  ${AlarmLogicalId}:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmActions:
        - Ref: SNSTopicARN
      AlarmDescription: 'Alarm by Digito for Elasticache Redis migration that indicates if the data in the ElastiCache primary node is not in sync with Redis on EC2'
      AlarmName: ${AlarmName}
      ComparisonOperator: LessThanThreshold
      EvaluationPeriods: 5
      DatapointsToAlarm: 1
      Dimensions:
        - Name: CacheClusterId
          Value: '${ClusterId}'
      MetricName: MasterLinkHealthStatus
      Namespace: AWS/ElastiCache
      Period: 60
      Statistic: Maximum
      Threshold: ${Threshold}
      TreatMissingData: missing
