AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SNSTopicARN:
    Type: String
Resources:
  ThrottlesAlarm:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmActions:
        - Ref: SNSTopicARN
      AlarmDescription:
        Fn::Join: [ '', [ 'Alarm by Digito that reports when sustained throttles occur' ] ]
      AlarmName: ${AlarmName}
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 3
      DatapointsToAlarm: 3
      Dimensions:
        - Name: FunctionName
          Value: '${FunctionName}'
      MetricName: Throttles
      Namespace: AWS/Lambda
      Period: 60
      Statistic: Maximum
      Threshold: ${Threshold}
      TreatMissingData: missing
    Metadata:
      'AWS::Digito::Monitoring':
        recommendationId: 'compute:alarm:lambda-throttles:2020-07-13'
