---
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SNSTopicARN:
    Type: String
Resources:
  ${AlarmLogicalId}:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmName: ${AlarmName}
      AlarmDescription: |
        Alarm by Digito that indicates that too many concurrent connections are open through the NAT gateway
        and the NAT gateway could not allocate a source port
      AlarmActions:
        - Ref: SNSTopicARN
      MetricName: ErrorPortAllocation
      Namespace: AWS/NATGateway
      Dimensions:
        - Name: NatGatewayId
          Value: ${NatGatewayId}
      Period: 60
      Statistic: Average
      Threshold: ${Threshold}
      EvaluationPeriods: 5
      DatapointsToAlarm: 3
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
