---
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SNSTopicARN:
    Type: String
Resources:
  ${AlarmLogicalId}:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmName: ${AlarmName}
      AlarmDescription: "Alarm by Digito for Amazon ECS that indicates if the percentage of memory that is reserved by running tasks in the cluster, is exceeding specified ${Threshold} limit"
      AlarmActions:
        - Ref: SNSTopicARN
      MetricName: MemoryReservation
      Namespace: AWS/ECS
      Dimensions:
        - Name: ClusterName
          Value: '${ClusterName}'
      Period: 60
      Statistic: Average
      Threshold: ${Threshold}
      EvaluationPeriods: 5
      DatapointsToAlarm: 3
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: missing
      Unit: Percent
