AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SNSTopicARN:
    Type: String
Resources:
  ${AlarmLogicalId}:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmActions:
        - Ref: SNSTopicARN
      AlarmDescription: 'Alarm by Digito for Kinesis Data Analytics for Apache Flink applications that tracks the overall percentage of CPU utilization across task managers, is exceeding specified ${Threshold} limit'
      AlarmName: ${AlarmName}
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: ${EvaluationPeriods}
      DatapointsToAlarm: ${DatapointsToAlarm}
      Dimensions:
        - Name: Application
          Value: '${KinesisAnalyticsAppName}'
      Namespace: AWS/KinesisAnalytics
      MetricName: cpuUtilization
      Period: 60
      Statistic: Maximum
      Threshold: ${Threshold}
      TreatMissingData: missing
