AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SNSTopicARN:
    Type: String
Resources:
  ${AlarmLogicalId}:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmActions:
        - Ref: SNSTopicARN
      AlarmDescription: 'Alarm by Digito that reports concurrent execution status'
      AlarmName: ${AlarmName}
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 5
      DatapointsToAlarm: 3
      Dimensions:
        - Name: FunctionName
          Value: '${FunctionName}'
      MetricName: ConcurrentExecutions
      Namespace: AWS/Lambda
      Period: 60
      Statistic: Average
      Threshold: ${Threshold}
      TreatMissingData: missing
