---
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SNSTopicARN:
    Type: String
Resources:
  ${AlarmLogicalId}:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmName: ${AlarmName}
      AlarmDescription: "Alarm by Digito that checks is there any message in DLQ? If so, it needs to be investigated as soon as possible."
      AlarmActions:
        - Ref: SNSTopicARN
      MetricName: ApproximateNumberOfMessagesVisible
      Namespace: AWS/SQS
      Dimensions:
        - Name: QueueName
          Value: ${QueueName}
      Period: 60
      Statistic: Sum
      Threshold: ${Threshold}
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
