AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SNSTopicARN:
    Type: String
Resources:
  ${AlarmLogicalId}:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmActions:
        - Ref: SNSTopicARN
      AlarmDescription: 'Digito alarm that tracks the 5xx responses received from API-Gateway. Triggers when the 5xx are over a 10 percent'
      AlarmName: ${AlarmName}
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 5
      DatapointsToAlarm: 3
      Dimensions:
        - Name: ApiName
          Value: '${ApiName}'
      MetricName: 5XXError
      Namespace: AWS/ApiGateway
      Period: 60
      ExtendedStatistic: p90
      Threshold: ${Threshold}
      TreatMissingData: missing
