AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SNSTopicARN:
    Type: String
Resources:
  ${AlarmLogicalId}:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmActions:
        - Ref: SNSTopicARN
      AlarmDescription: 'Alarm by Digito that indicates when the amount of available random access memory is less then or equal ${Threshold}'
      AlarmName: ${AlarmName}
      ComparisonOperator: LessThanOrEqualToThreshold
      EvaluationPeriods: 5
      DatapointsToAlarm: 3
      Dimensions:
        - Name: DBInstanceIdentifier
          Value: '${DBInstancePrimaryIdentifier}'
      MetricName: FreeableMemory
      Namespace: AWS/DocDB
      Period: 60
      Statistic: Minimum
      Threshold: ${Threshold}
      TreatMissingData: missing
