---
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SNSTopicARN:
    Type: String
Resources:
  ${AlarmLogicalId}:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmName: ${AlarmName}
      AlarmDescription: "Alarm by Digito that reports when replication from one replica table to another takes too much time"
      AlarmActions:
        - Ref: SNSTopicARN
      MetricName: ReplicationLatency
      Namespace: AWS/DynamoDB
      Dimensions:
        - Name: TableName
          Value: ${DynamoDbTable}
        - Name: ReceivingRegion
          Value: ${Region}
      Period: 60
      Statistic: Maximum
      Threshold: ${Threshold}
      EvaluationPeriods: 5
      DatapointsToAlarm: 3
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: missing
