#
# Copyright 2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this
# software and associated documentation files (the "Software"), to deal in the Software
# without restriction, including without limitation the rights to use, copy, modify,
# merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
# PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
---
AWSTemplateFormatVersion: 2010-09-09
Description: Test stack for Athena and related resources. Contains all alarms
Outputs:
  AthenaWorkGroup:
    Description: Athena WorkGroup name
    Value: !Ref  AthenaWorkGroup
#  RoleApproveCleanBucketArn:
#    Description: ARN of RoleApproveCleanBucket
#    Value: !GetAtt RoleApproveCleanBucket.Arn
##  S3OutputBucket:
#    Description: S3 Bucket Name
#    Value: !Ref S3OutputBucket
#  S3CrawlerBucket:
#    Description: S3 Bucket Name
#    Value: !Ref S3CrawlerBucket
#  GlueDataBase:
#    Description: Glue DataBase Name
#    Value: !Ref GlueDataBase

Parameters:
  CleanupS3BucketLambdaArn:
    Description: ARN of Cleanup S3 Bucket Lambda Function
    Type: String

Resources:
  AthenaWorkGroup:
    Type: 'AWS::Athena::WorkGroup'
    Properties:
      Description: Test WorkGroup for Athena
      Name: !Join
        - "-"
        - - "digito-workgroup"
          - !Select
            - 0
            - !Split
              - "-"
              - !Select
                - 2
                - !Split
                  - "/"
                  - !Ref "AWS::StackId"
      RecursiveDeleteOption: true
      WorkGroupConfiguration:
        PublishCloudWatchMetricsEnabled: true
        ResultConfiguration:
          OutputLocation: !Join [ "", [ "s3://" , Ref: S3OutputBucket, "/" ] ]

  GlueDataBase:
    Type: 'AWS::Glue::Database'
    Properties:
      CatalogId: !Ref 'AWS::AccountId'
      DatabaseInput:
        Description: Test database for Athena service
        Name: !Join
          - "-"
          - - "athena-test-database"
            - !Select
              - 0
              - !Split
                - "-"
                - !Select
                  - 2
                  - !Split
                    - "/"
                    - !Ref "AWS::StackId"

  GlueCrawler:
    Type: AWS::Glue::Crawler
    Properties:
      Name: !Join
        - "-"
        - - "cfn-crawler"
          - !Select
            - 0
            - !Split
              - "-"
              - !Select
                - 2
                - !Split
                  - "/"
                  - !Ref "AWS::StackId"
      Description: AWS Glue crawler to crawl flights data
      DatabaseName: !Ref GlueDataBase
      Role: !GetAtt GlueRole.Arn
      SchemaChangePolicy:
        UpdateBehavior: "UPDATE_IN_DATABASE"
        DeleteBehavior: "LOG"
      TablePrefix: 'cfn_table_1_'
      Targets:
        S3Targets:
#          - Path: !Join [ "", [ "s3://" , Ref: S3CrawlerBucket, "/" ] ]
          - Path: "s3://crawler-public-us-east-1/flight/2016/csv"
  #      Configuration: "{\"Version\":1.0,\"CrawlerOutput\":{\"Partitions\":{\"AddOrUpdateBehavior\":\"InheritFromTable\"},\"Tables\":{\"AddOrUpdateBehavior\":\"MergeNewColumns\"}}}"

  GlueRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "glue.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: "root"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: "*"
                Resource: "*"

  S3OutputBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      BucketName: !Join
        - "-"
        - - "s3-athena-output-bucket"
          - !Select
            - 0
            - !Split
              - "-"
              - !Select
                - 2
                - !Split
                  - "/"
                  - !Ref "AWS::StackId"
      AccessControl: Private

  S3CrawlerBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      BucketName: !Join
        - "-"
        - - "s3-athena-crawler-bucket"
          - !Select
            - 0
            - !Split
              - "-"
              - !Select
                - 2
                - !Split
                  - "/"
                  - !Ref "AWS::StackId"
      AccessControl: Private


  # To clean S3 buckets before deleting stack.
  CleanupS3BucketsOnDelete:
    Type: Custom::CleanupS3BucketsOnDelete
    Properties:
      ServiceToken: !Ref CleanupS3BucketLambdaArn
      BucketNames:
        - !Ref S3OutputBucket
        - !Ref S3CrawlerBucket

#  RoleApproveCleanBucket:
#    Type: AWS::IAM::Role
#    Properties:
#      AssumeRolePolicyDocument:
#        Version: 2012-10-17
#        Statement:
#          - Effect: Allow
#            Principal:
#              AWS: !Ref "AWS::AccountId"
#            Action:
#              - sts:AssumeRole
#
#  PolicyApproveCleanBucket:
#    Type: AWS::IAM::Policy
#    Properties:
#      PolicyName: DigitoRestoreFromBackupAssumePolicy
#      PolicyDocument:
#        Version: 2012-10-17
#        Statement:
#          - Effect: Allow
#            Resource: "*"
#            Action:
#              - ssm:SendAutomationSignal
#      Roles:
#        - Ref: RoleApproveCleanBucket


