#
# We use this downstream. Please do not delete
#
# Copyright 2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this
# software and associated documentation files (the "Software"), to deal in the Software
# without restriction, including without limitation the rights to use, copy, modify,
# merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
# PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
---
AWSTemplateFormatVersion: 2010-09-09
Description: Test stack for Amazon DocumentDb cluster and related resources. With three replicas.
Outputs:
  DBClusterIdentifier:
    Value: !Ref DBCluster
  DBInstancePrimaryIdentifier:
    Value: !Ref DBInstancePrimary
  DBInstanceReplicaIdentifier:
    Value: !Ref DBInstanceReplica1
  ClusterEndpoint:
    Value: !GetAtt DBCluster.Endpoint
  ClusterPort:
    Value: !GetAtt DBCluster.Port
  ClusterResourceId:
    Value: !GetAtt DBCluster.ClusterResourceId
  EngineVersion:
    Value: "4.0.0"
  VPCSecurityGroupId:
    Value: !Ref VPCSecurityGroup
Parameters:
  DBInstanceClass:
    Description: "Instance class. Please refer to: https://docs.aws.amazon.com/documentdb/latest/developerguide/db-instance-classes.html#db-instance-classes-by-region"
    Type: "String"
    Default: "db.t3.medium"
  VPC:
    Type: String
    Description: VPC ID
  VPCCIDR:
    Type: String
    Description: IP Address range for the VPC
    MinLength: '9'
    MaxLength: '18'
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: Valid IP CIDR range of the form x.x.x.x/x.
  PrivateSubnet01:
    Type: String
    Description: PrivateSubnet ID
  PrivateSubnet02:
    Type: String
    Description: PrivateSubnet ID
  DbClusterPort:
    Type: Number
    Description: DocDb cluster port
    Default: 27017
  KmsKey:
    Type: String
    Description: The ARN for KMS key for encryption
    AllowedPattern: 'arn:aws:kms:\S+:\d+:key\/\S+'
Resources:
  GeneratedSecretString:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Generated DocumentDb cluster password
      GenerateSecretString:
        SecretStringTemplate: '{"username": "admindb"}'
        GenerateStringKey: "password"
        PasswordLength: 16
        ExcludeCharacters: "\"@/\\"

  VPCSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: VPC Security Group of DocumentDB cluster for Digito scenarios
      SecurityGroupEgress: []
      SecurityGroupIngress:
        - CidrIp:
            Ref: VPCCIDR
          FromPort:
            Ref: DbClusterPort
          IpProtocol: TCP
          ToPort:
            Ref: DbClusterPort
        - CidrIp:
            Ref: VPCCIDR
          FromPort:
            Ref: DbClusterPort
          IpProtocol: TCP
          ToPort:
            Ref: DbClusterPort
      VpcId:
        Ref: VPC

  DBCluster:
    Type: "AWS::DocDB::DBCluster"
    DeletionPolicy: Delete
    Properties:
      DBClusterIdentifier: !Join
        - "-"
        - - "dbcluster"
          - !Select
            - 0
            - !Split
              - "-"
              - !Select
                - 2
                - !Split
                  - "/"
                  - !Ref "AWS::StackId"
      MasterUsername: !Sub '{{resolve:secretsmanager:${GeneratedSecretString}::username}}'
      MasterUserPassword: !Sub '{{resolve:secretsmanager:${GeneratedSecretString}::password}}'
      StorageEncrypted: true
      EngineVersion: 4.0.0
      VpcSecurityGroupIds:
        - !GetAtt VPCSecurityGroup.GroupId
      DBSubnetGroupName: !Ref DocDbClusterSubnetGroup
      KmsKeyId: !Ref KmsKey

  DocDbClusterSubnetGroup:
    Type: "AWS::DocDB::DBSubnetGroup"
    Properties:
      DBSubnetGroupDescription: "DocumentDB cluster subnet group"
      SubnetIds:
        - !Ref PrivateSubnet01
        - !Ref PrivateSubnet02

  DBInstancePrimary:
    Type: "AWS::DocDB::DBInstance"
    Properties:
      DBClusterIdentifier: !Ref DBCluster
      DBInstanceIdentifier: !Join
        - "-"
        - - "dbinstance01"
          - !Ref "AWS::Region"
          - !Ref "AWS::AccountId"
          - !Select
            - 0
            - !Split
              - "-"
              - !Select
                - 2
                - !Split
                  - "/"
                  - !Ref "AWS::StackId"
      DBInstanceClass: !Ref DBInstanceClass

  DBInstanceReplica1:
    Type: "AWS::DocDB::DBInstance"
    Properties:
      DBClusterIdentifier: !Ref DBCluster
      DBInstanceIdentifier: !Join
        - "-"
        - - "dbinstance02"
          - !Ref "AWS::Region"
          - !Ref "AWS::AccountId"
          - !Select
            - 0
            - !Split
              - "-"
              - !Select
                - 2
                - !Split
                  - "/"
                  - !Ref "AWS::StackId"
      DBInstanceClass: !Ref DBInstanceClass
    DependsOn: DBInstancePrimary

  DBInstanceReplica2:
    Type: "AWS::DocDB::DBInstance"
    Properties:
      DBClusterIdentifier: !Ref DBCluster
      DBInstanceIdentifier: !Join
        - "-"
        - - "dbinstance03"
          - !Ref "AWS::Region"
          - !Ref "AWS::AccountId"
          - !Select
            - 0
            - !Split
              - "-"
              - !Select
                - 2
                - !Split
                  - "/"
                  - !Ref "AWS::StackId"
      DBInstanceClass: !Ref DBInstanceClass
    DependsOn: DBInstancePrimary

  DBInstanceReplica3:
    Type: "AWS::DocDB::DBInstance"
    Properties:
      DBClusterIdentifier: !Ref DBCluster
      DBInstanceIdentifier: !Join
        - "-"
        - - "dbinstance04"
          - !Ref "AWS::Region"
          - !Ref "AWS::AccountId"
          - !Select
            - 0
            - !Split
              - "-"
              - !Select
                - 2
                - !Split
                  - "/"
                  - !Ref "AWS::StackId"
      DBInstanceClass: !Ref DBInstanceClass
    DependsOn: DBInstancePrimary

