#
# Copyright 2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this
# software and associated documentation files (the "Software"), to deal in the Software
# without restriction, including without limitation the rights to use, copy, modify,
# merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
# PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
---
AWSTemplateFormatVersion: 2010-09-09
Description: Test stack for DynamoDB and related resources. Contains all alarms
Parameters:
  DynamoDBTableName:
    Type: String
    Description: The DynamoDB Table Name
    Default: digito-dynamodb-table
Outputs:
  DynamoDBTable:
    Description: The DynamoDB Table Name
    Value: !Ref DynamoDBTable
  KinesisStreamArn:
    Description: The Kinesis Data Stream
    Value: !GetAtt KinesisDataStream.Arn
  DynamoDBTableARN:
    Description: The DynamoDB Table ARN
    Value: !GetAtt DynamoDBTable.Arn
  WriteThrottleEventsAlarmName:
    Description: Alarm
    Value: !Ref WriteThrottleEventsAlarm
  ReadThrottleEventsAlarmName:
    Description: Alarm
    Value: !Ref ReadThrottleEventsAlarm
  ThrottledRequestsAlarmName:
    Description: Alarm
    Value: !Ref ThrottledRequestsAlarm
  ConditionalCheckFailedRequestsAlarmmName:
    Description: Alarm
    Value: !Ref ConditionalCheckFailedRequestsAlarm
  UserErrorsAlarmName:
    Description: Alarm
    Value: !Ref UserErrorsAlarm
  SystemErrorsAlarmName:
    Description: Alarm
    Value: !Ref SystemErrorsAlarm
  TransactionConflictAlarmName:
    Description: Alarm
    Value: !Ref TransactionConflictAlarm
  OnlineIndexThrottleEventsAlarmName:
    Description: Alarm
    Value: !Ref OnlineIndexThrottleEventsAlarm
  SuccessfulRequestLatencyAlarmName:
    Description: Alarm
    Value: !Ref SuccessfulRequestLatencyAlarm
  AccountProvisionedReadCapacityUtilizationAlarmName:
    Description: Alarm
    Value: !Ref AccountProvisionedReadCapacityUtilizationAlarm
  AccountProvisionedWriteCapacityUtilizationAlarmName:
    Description: Alarm
    Value: !Ref AccountProvisionedWriteCapacityUtilizationAlarm
  MaxProvisionedTableReadCapacityUtilizationAlarmName:
    Description: Alarm
    Value: !Ref MaxProvisionedTableReadCapacityUtilizationAlarm
  MaxProvisionedTableWriteCapacityUtilizationAlarmName:
    Description: Alarm
    Value: !Ref MaxProvisionedTableWriteCapacityUtilizationAlarm
  PendingReplicationCountAlarmName:
    Description: Alarm
    Value: !Ref PendingReplicationCountAlarm
  ReplicationLatencyAlarmName:
    Description: Alarm
    Value: !Ref ReplicationLatencyAlarm
Resources:
  KinesisDataStream:
    Type: AWS::Kinesis::Stream
    Properties:
      Name: DigitoKinesisDataStream
      RetentionPeriodHours: 168
      ShardCount: 2
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      AttributeDefinitions:
        - AttributeName: "USER_ID"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "USER_ID"
          KeyType: "HASH"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      Tags:
        - Key: Key
          Value: Value
  WriteCapacityScalableTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Properties:
      MaxCapacity: 15
      MinCapacity: 5
      ResourceId: !Join
        - /
        - - table
          - !Ref DynamoDBTable
      RoleARN: !GetAtt ScalingRole.Arn
      ScalableDimension: dynamodb:table:WriteCapacityUnits
      ServiceNamespace: dynamodb
  ScalingRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - application-autoscaling.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        -
          PolicyName: "root"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action:
                  - "dynamodb:DescribeTable"
                  - "dynamodb:UpdateTable"
                  - "cloudwatch:PutMetricAlarm"
                  - "cloudwatch:DescribeAlarms"
                  - "cloudwatch:GetMetricStatistics"
                  - "cloudwatch:SetAlarmState"
                  - "cloudwatch:DeleteAlarms"
                Resource: "*"
  WriteScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: WriteAutoScalingPolicy
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref WriteCapacityScalableTarget
      TargetTrackingScalingPolicyConfiguration:
        TargetValue: 50.0
        ScaleInCooldown: 60
        ScaleOutCooldown: 60
        PredefinedMetricSpecification:
          PredefinedMetricType: DynamoDBWriteCapacityUtilization
  ##### Health Alarms #####
  WriteThrottleEventsAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmName: WriteThrottleEvents
      AlarmDescription: "dynamodb:alarm:health-write_throttle_events:2020-04-01"
      ActionsEnabled: true
      MetricName: WriteThrottleEvents
      Namespace: AWS/DynamoDB
      Statistic: Sum
      Dimensions:
        - Name: TableName
          Value: !Ref DynamoDBTable
      Period: 60
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Threshold: 1
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: missing
      Unit: Count
  ReadThrottleEventsAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmName: ReadThrottleEvents
      AlarmDescription: "dynamodb:alarm:health-read_throttle_events:2020-04-01"
      ActionsEnabled: true
      MetricName: ReadThrottleEvents
      Namespace: AWS/DynamoDB
      Statistic: Sum
      Dimensions:
        - Name: TableName
          Value: !Ref DynamoDBTable
      Period: 60
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Threshold: 1
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: missing
      Unit: Count
  ThrottledRequestsAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmName: ThrottledRequests
      AlarmDescription: "dynamodb:alarm:health-throttled_requests:2020-04-01"
      ActionsEnabled: true
      MetricName: ThrottledRequests
      Namespace: AWS/DynamoDB
      Statistic: Sum
      Dimensions:
        - Name: TableName
          Value: !Ref DynamoDBTable
      Period: 60
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Threshold: 1
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: missing
      Unit: Count
  ConditionalCheckFailedRequestsAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmName: ConditionalCheckFailedRequests
      AlarmDescription: "dynamodb:alarm:health-conditional_check_failed_requests:2020-04-01"
      ActionsEnabled: true
      MetricName: ConditionalCheckFailedRequests
      Namespace: AWS/DynamoDB
      Statistic: Sum
      Dimensions:
        - Name: TableName
          Value: !Ref DynamoDBTable
      Period: 60
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Threshold: 1
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: missing
      Unit: Count
  UserErrorsAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmName: UserErrors
      AlarmDescription: "dynamodb:alarm:health-user_errors:2020-04-01"
      ActionsEnabled: true
      MetricName: UserErrors
      Namespace: AWS/DynamoDB
      Statistic: Sum
      Dimensions:
        - Name: TableName
          Value: !Ref DynamoDBTable
      Period: 60
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Threshold: 1
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: missing
      Unit: Count
  SystemErrorsAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmName: SystemErrors
      AlarmDescription: "dynamodb:alarm:health-system_errors:2020-04-01"
      ActionsEnabled: true
      MetricName: SystemErrors
      Namespace: AWS/DynamoDB
      Statistic: Sum
      Dimensions:
        - Name: TableName
          Value: !Ref DynamoDBTable
      Period: 60
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Threshold: 1
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: missing
      Unit: Count
  TransactionConflictAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmName: TransactionConflict
      AlarmDescription: "dynamodb:alarm:health-transaction_conflict:2020-04-01"
      ActionsEnabled: true
      MetricName: TransactionConflict
      Namespace: AWS/DynamoDB
      Statistic: Sum
      Dimensions:
        - Name: TableName
          Value: !Ref DynamoDBTable
      Period: 60
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Threshold: 1
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: missing
      Unit: Count
  OnlineIndexThrottleEventsAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmName: OnlineIndexThrottleEvents
      AlarmDescription: "dynamodb:alarm:health-online_index_throttle_events:2020-04-01"
      ActionsEnabled: true
      MetricName: OnlineIndexThrottleEvents
      Namespace: AWS/DynamoDB
      Statistic: Maximum
      Dimensions:
        - Name: TableName
          Value: !Ref DynamoDBTable
      Period: 60
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Threshold: 10
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: missing
      Unit: Count
  SuccessfulRequestLatencyAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmName: SuccessfulRequestLatency
      AlarmDescription: "dynamodb:alarm:health-successful_request_latency:2020-04-01"
      ActionsEnabled: true
      MetricName: SuccessfulRequestLatency
      Namespace: AWS/DynamoDB
      Statistic: Maximum
      Dimensions:
        - Name: TableName
          Value: !Ref DynamoDBTable
      Period: 60
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Threshold: 100
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: missing
      Unit: Milliseconds
  AccountProvisionedReadCapacityUtilizationAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmName: AccountProvisionedReadCapacityUtilization
      AlarmDescription: "dynamodb:alarm:health-account_read_capacity_utilization:2020-04-01"
      ActionsEnabled: true
      MetricName: AccountProvisionedReadCapacityUtilization
      Namespace: AWS/DynamoDB
      Statistic: Maximum
      Dimensions:
        - Name: TableName
          Value: !Ref DynamoDBTable
      Period: 60
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Threshold: 85
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: missing
      Unit: Percent
  AccountProvisionedWriteCapacityUtilizationAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmName: AccountProvisionedWriteCapacityUtilization
      AlarmDescription: "dynamodb:alarm:health-account_write_capacity_utilization:2020-04-01"
      ActionsEnabled: true
      MetricName: AccountProvisionedWriteCapacityUtilization
      Namespace: AWS/DynamoDB
      Statistic: Maximum
      Dimensions:
        - Name: TableName
          Value: !Ref DynamoDBTable
      Period: 60
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Threshold: 85
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: missing
      Unit: Percent
  MaxProvisionedTableReadCapacityUtilizationAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmName: MaxProvisionedTableReadCapacityUtilization
      AlarmDescription: "dynamodb:alarm:health-table_read_utilization:2020-04-01"
      ActionsEnabled: true
      MetricName: MaxProvisionedTableReadCapacityUtilization
      Namespace: AWS/DynamoDB
      Statistic: Maximum
      Dimensions:
        - Name: TableName
          Value: !Ref DynamoDBTable
      Period: 60
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Threshold: 85
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: missing
      Unit: Percent
  MaxProvisionedTableWriteCapacityUtilizationAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmName: MaxProvisionedTableWriteCapacityUtilization
      AlarmDescription: "dynamodb:alarm:health-table_write_utilization:2020-04-01"
      ActionsEnabled: true
      MetricName: MaxProvisionedTableWriteCapacityUtilization
      Namespace: AWS/DynamoDB
      Statistic: Maximum
      Dimensions:
        - Name: TableName
          Value: !Ref DynamoDBTable
      Period: 60
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Threshold: 85
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: missing
      Unit: Percent

  ##### Recovery Alarms #####
  PendingReplicationCountAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmName: PendingReplicationCount
      AlarmDescription: "dynamodb:alarm:recovery-pending_replication_count:2020-04-01"
      ActionsEnabled: true
      MetricName: PendingReplicationCount
      Namespace: AWS/DynamoDB
      Statistic: Sum
      Dimensions:
        - Name: TableName
          Value: !Ref DynamoDBTable
      Period: 60
      EvaluationPeriods: 5
      DatapointsToAlarm: 3
      Threshold: 100
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: missing
      Unit: Count
  ReplicationLatencyAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmName: ReplicationLatency
      AlarmDescription: "dynamodb:alarm:recovery-replication_latency:2020-04-01"
      ActionsEnabled: true
      MetricName: ReplicationLatency
      Namespace: AWS/DynamoDB
      Statistic: Maximum
      Dimensions:
        - Name: TableName
          Value: !Ref DynamoDBTable
      Period: 60
      EvaluationPeriods: 5
      DatapointsToAlarm: 3
      Threshold: 10
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: missing
      Unit: Milliseconds
