#
# Copyright 2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this
# software and associated documentation files (the "Software"), to deal in the Software
# without restriction, including without limitation the rights to use, copy, modify,
# merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
# PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
---
AWSTemplateFormatVersion: 2010-09-09
Description: Test stack for DynamoDB and related resources. Contains all alarms
Outputs:
  DynamoDBTableName:
    Description: The DynamoDB Table Name
    Value: !Ref DynamoDBTable
  DynamoDBTableARN:
    Description: The DynamoDB Table ARN
    Value: !GetAtt DynamoDBTable.Arn
  WriteThrottleEventsAlarmName:
    Description: Alarm
    Value: !Ref  WriteThrottleEventsAlarm
  ReadThrottleEventsAlarmName:
    Description: Alarm
    Value: !Ref  ReadThrottleEventsAlarm
  ThrottledRequestsAlarmName:
    Description: Alarm
    Value: !Ref  ThrottledRequestsAlarm
  ConditionalCheckFailedRequestsAlarmmName:
    Description: Alarm
    Value: !Ref  ConditionalCheckFailedRequestsAlarm
  UserErrorsAlarmName:
    Description: Alarm
    Value: !Ref  UserErrorsAlarm
  SystemErrorsAlarmName:
    Description: Alarm
    Value: !Ref  SystemErrorsAlarm
  TransactionConflictAlarmName:
    Description: Alarm
    Value: !Ref  TransactionConflictAlarm
  OnlineIndexThrottleEventsAlarmName:
    Description: Alarm
    Value: !Ref  OnlineIndexThrottleEventsAlarm
  SuccessfulRequestLatencyAlarmName:
    Description: Alarm
    Value: !Ref  SuccessfulRequestLatencyAlarm
  AccountProvisionedReadCapacityUtilizationAlarmName:
    Description: Alarm
    Value: !Ref  AccountProvisionedReadCapacityUtilizationAlarm
  AccountProvisionedWriteCapacityUtilizationAlarmName:
    Description: Alarm
    Value: !Ref  AccountProvisionedWriteCapacityUtilizationAlarm
  MaxProvisionedTableReadCapacityUtilizationAlarmName:
    Description: Alarm
    Value: !Ref  MaxProvisionedTableReadCapacityUtilizationAlarm
  MaxProvisionedTableWriteCapacityUtilizationAlarmName:
    Description: Alarm
    Value: !Ref  MaxProvisionedTableWriteCapacityUtilizationAlarm
  PendingReplicationCountAlarmName:
    Description: Alarm
    Value: !Ref  PendingReplicationCountAlarm
  ReplicationLatencyAlarmName:
    Description: Alarm
    Value: !Ref  ReplicationLatencyAlarm
Resources:
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Join
        - "-"
        - - "dynamo-db-table-digito"
          - !Ref "AWS::Region"
          - !Ref "AWS::AccountId"
          - !Select
            - 0
            - !Split
              - "-"
              - !Select
                - 2
                - !Split
                  - "/"
                  - !Ref "AWS::StackId"
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      AttributeDefinitions:
        - AttributeName: "USER_ID"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "USER_ID"
          KeyType: "HASH"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  WriteThrottleEventsAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmDescription: "dynamodb:alarm:health-write_throttle_events:2020-04-01"
      ActionsEnabled: false
      MetricName: WriteThrottleEvents
      Namespace: AWS/DynamoDB
      Statistic: Sum
      Dimensions:
        - Name: TableName
          Value: !Ref DynamoDBTable
      Period: 60
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: notBreaching
      Unit: Count

  ReadThrottleEventsAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmDescription: "dynamodb:alarm:health-read_throttle_events:2020-04-01"
      ActionsEnabled: false
      MetricName: ReadThrottleEvents
      Namespace: AWS/DynamoDB
      Statistic: Sum
      Dimensions:
        - Name: TableName
          Value: !Ref DynamoDBTable
      Period: 60
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: notBreaching
      Unit: Count

  ThrottledRequestsAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmDescription: "dynamodb:alarm:health-throttled_requests:2020-04-01"
      ActionsEnabled: false
      MetricName: ThrottledRequests
      Namespace: AWS/DynamoDB
      Statistic: Sum
      Dimensions:
        - Name: TableName
          Value: !Ref DynamoDBTable
      Period: 60
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: notBreaching
      Unit: Count

  ConditionalCheckFailedRequestsAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmDescription: "dynamodb:alarm:health-conditional_check_failed_requests:2020-04-01"
      ActionsEnabled: false
      MetricName: ConditionalCheckFailedRequests
      Namespace: AWS/DynamoDB
      Statistic: Sum
      Dimensions:
        - Name: TableName
          Value: !Ref DynamoDBTable
      Period: 60
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: notBreaching
      Unit: Count

  UserErrorsAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmDescription: "dynamodb:alarm:health-user_errors:2020-04-01"
      ActionsEnabled: false
      MetricName: UserErrors
      Namespace: AWS/DynamoDB
      Statistic: Sum
      Dimensions:
        - Name: TableName
          Value: !Ref DynamoDBTable
      Period: 60
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: notBreaching
      Unit: Count

  SystemErrorsAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmDescription: "dynamodb:alarm:health-system_errors:2020-04-01"
      ActionsEnabled: false
      MetricName: SystemErrors
      Namespace: AWS/DynamoDB
      Statistic: Sum
      Dimensions:
        - Name: TableName
          Value: !Ref DynamoDBTable
      Period: 60
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: notBreaching
      Unit: Count

  TransactionConflictAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmDescription: "dynamodb:alarm:health-transaction_conflict:2020-04-01"
      ActionsEnabled: false
      MetricName: TransactionConflict
      Namespace: AWS/DynamoDB
      Statistic: Sum
      Dimensions:
        - Name: TableName
          Value: !Ref DynamoDBTable
      Period: 60
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: notBreaching
      Unit: Count

  OnlineIndexThrottleEventsAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmDescription: "dynamodb:alarm:health-online_index_throttle_events:2020-04-01"
      ActionsEnabled: false
      MetricName: OnlineIndexThrottleEvents
      Namespace: AWS/DynamoDB
      Statistic: Maximum
      Dimensions:
        - Name: TableName
          Value: !Ref DynamoDBTable
      Period: 60
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Threshold: 10
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      Unit: Count

  SuccessfulRequestLatencyAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmDescription: "dynamodb:alarm:health-successful_request_latency:2020-04-01"
      ActionsEnabled: false
      MetricName: SuccessfulRequestLatency
      Namespace: AWS/DynamoDB
      Statistic: Maximum
      Dimensions:
        - Name: TableName
          Value: !Ref DynamoDBTable
      Period: 60
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Threshold: 100
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      Unit: Milliseconds

  AccountProvisionedReadCapacityUtilizationAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmDescription: "dynamodb:alarm:health-account_read_capacity_utilization:2020-04-01"
      ActionsEnabled: false
      MetricName: AccountProvisionedReadCapacityUtilization
      Namespace: AWS/DynamoDB
      Statistic: Maximum
      Dimensions:
        - Name: TableName
          Value: !Ref DynamoDBTable
      Period: 60
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Threshold: 85
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      Unit: Percent

  AccountProvisionedWriteCapacityUtilizationAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmDescription: "dynamodb:alarm:health-account_write_capacity_utilization:2020-04-01"
      ActionsEnabled: false
      MetricName: AccountProvisionedWriteCapacityUtilization
      Namespace: AWS/DynamoDB
      Statistic: Maximum
      Dimensions:
        - Name: TableName
          Value: !Ref DynamoDBTable
      Period: 60
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Threshold: 85
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      Unit: Percent

  MaxProvisionedTableReadCapacityUtilizationAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmDescription: "dynamodb:alarm:health-table_read_utilization:2020-04-01"
      ActionsEnabled: false
      MetricName: MaxProvisionedTableReadCapacityUtilization
      Namespace: AWS/DynamoDB
      Statistic: Maximum
      Dimensions:
        - Name: TableName
          Value: !Ref DynamoDBTable
      Period: 60
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Threshold: 85
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      Unit: Percent

  MaxProvisionedTableWriteCapacityUtilizationAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmDescription: "dynamodb:alarm:health-table_write_utilization:2020-04-01"
      ActionsEnabled: false
      MetricName: MaxProvisionedTableWriteCapacityUtilization
      Namespace: AWS/DynamoDB
      Statistic: Maximum
      Dimensions:
        - Name: TableName
          Value: !Ref DynamoDBTable
      Period: 60
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Threshold: 85
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      Unit: Percent

  PendingReplicationCountAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmDescription: "dynamodb:alarm:recovery-pending_replication_count:2020-04-01"
      ActionsEnabled: false
      MetricName: PendingReplicationCount
      Namespace: AWS/DynamoDB
      Statistic: Sum
      Dimensions:
        - Name: TableName
          Value: !Ref DynamoDBTable
      Period: 60
      EvaluationPeriods: 5
      DatapointsToAlarm: 3
      Threshold: 100
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      Unit: Count

  ReplicationLatencyAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmDescription: "dynamodb:alarm:recovery-replication_latency:2020-04-01"
      ActionsEnabled: false
      MetricName: ReplicationLatency
      Namespace: AWS/DynamoDB
      Statistic: Maximum
      Dimensions:
        - Name: TableName
          Value: !Ref DynamoDBTable
      Period: 60
      EvaluationPeriods: 5
      DatapointsToAlarm: 3
      Threshold: 10
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      Unit: Milliseconds
