#
# Copyright 2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this
# software and associated documentation files (the "Software"), to deal in the Software
# without restriction, including without limitation the rights to use, copy, modify,
# merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
# PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
---
AWSTemplateFormatVersion: 2010-09-09
Description: Test stack for EFS and related resources. Contains all alarms
Parameters:
  VPCCidr:
    Type: String
    Description: VPC cidr block
    Default: 10.0.0.0/16
  AlarmIOThreshold:
    Type: Number
    Description: Alarm threshold for PercentIOLimitAlarm
    Default: 90
  AlarmClientConnectionsThreshold:
    Type: Number
    Description: Alarm threshold for ClientConnectionsAlarm
    Default: 1
  MountPoint:
    Description: The Linux mount point for the EFS volume
    Type: String
    MinLength: '1'
    Default: '/mnt/myEFSvolume'
  InstanceType:
    Description: The AWS instance type
    Type: String
    MinLength: '1'
    Default: 't3.micro'
Outputs:
  EFSID:
    Description: EFS ID
    Value: !GetAtt FileSystem.FileSystemId
  EFSMountTarget:
    Description: EFS Mount target ID
    Value: !Ref EFSMountTarget
  JobIAMRoleArn:
    Description: JobIAMRole ARN
    Value: !GetAtt JobIAMRole.Arn
  BackupVaultSourceName:
    Description: Backup Source Vault Name
    Value: !Ref  BackupVaultSource
  BackupVaultDestinationName:
    Description: Backup Dest Vault Name
    Value: !Ref  BackupVaultDestination
  EFSMountTargetSecurityGroupId:
    Description: Security Group Id
    Value: !GetAtt EFSMountTargetSecurityGroup.GroupId
  ClientConnectionsAlarmName:
    Description: Client Connections Alarm Name
    Value: !Ref  ClientConnectionsAlarm
  PercentIOLimitAlarmName:
    Description: Percent IO Limit Alarm Name
    Value: !Ref  PercentIOLimitAlarm
  MountFailureAlarmName:
    Description: Mount Failure Alarm Name
    Value: !Ref  MountFailureAlarm
  InstanceId:
    Description: EC2 Instance Id
    Value: !Ref Ec2Instance
  EFSUtilLogGroupName:
    Description: LogGroup where EFS Util write logs to
    Value: !Ref EFSLogGroup
Mappings:
  AWSInstanceType2Arch:
    t1.micro:
      Arch: HVM64
    t2.nano:
      Arch: HVM64
    t2.micro:
      Arch: HVM64
    t2.small:
      Arch: HVM64
    t2.medium:
      Arch: HVM64
    t2.large:
      Arch: HVM64
    t3.micro:
      Arch: HVM64
    m1.small:
      Arch: HVM64
    m1.medium:
      Arch: HVM64
    m1.large:
      Arch: HVM64
    m1.xlarge:
      Arch: HVM64
    m2.xlarge:
      Arch: HVM64
    m2.2xlarge:
      Arch: HVM64
    m2.4xlarge:
      Arch: HVM64
    m3.medium:
      Arch: HVM64
    m3.large:
      Arch: HVM64
    m3.xlarge:
      Arch: HVM64
    m3.2xlarge:
      Arch: HVM64
    m4.large:
      Arch: HVM64
    m4.xlarge:
      Arch: HVM64
    m4.2xlarge:
      Arch: HVM64
    m4.4xlarge:
      Arch: HVM64
    m4.10xlarge:
      Arch: HVM64
    c1.medium:
      Arch: HVM64
    c1.xlarge:
      Arch: HVM64
    c3.large:
      Arch: HVM64
    c3.xlarge:
      Arch: HVM64
    c3.2xlarge:
      Arch: HVM64
    c3.4xlarge:
      Arch: HVM64
    c3.8xlarge:
      Arch: HVM64
    c4.large:
      Arch: HVM64
    c4.xlarge:
      Arch: HVM64
    c4.2xlarge:
      Arch: HVM64
    c4.4xlarge:
      Arch: HVM64
    c4.8xlarge:
      Arch: HVM64
    g2.2xlarge:
      Arch: HVMG2
    g2.8xlarge:
      Arch: HVMG2
    r3.large:
      Arch: HVM64
    r3.xlarge:
      Arch: HVM64
    r3.2xlarge:
      Arch: HVM64
    r3.4xlarge:
      Arch: HVM64
    r3.8xlarge:
      Arch: HVM64
    i2.xlarge:
      Arch: HVM64
    i2.2xlarge:
      Arch: HVM64
    i2.4xlarge:
      Arch: HVM64
    i2.8xlarge:
      Arch: HVM64
    d2.xlarge:
      Arch: HVM64
    d2.2xlarge:
      Arch: HVM64
    d2.4xlarge:
      Arch: HVM64
    d2.8xlarge:
      Arch: HVM64
    hi1.4xlarge:
      Arch: HVM64
    hs1.8xlarge:
      Arch: HVM64
    cr1.8xlarge:
      Arch: HVM64
    cc2.8xlarge:
      Arch: HVM64
  AWSRegionArch2AMI:
    us-east-1:
      HVM64: ami-0ff8a91507f77f867
      HVMG2: ami-0a584ac55a7631c0c
    us-west-2:
      HVM64: ami-a0cfeed8
      HVMG2: ami-0e09505bc235aa82d
    us-west-1:
      HVM64: ami-0bdb828fd58c52235
      HVMG2: ami-066ee5fd4a9ef77f1
    eu-west-1:
      HVM64: ami-047bb4163c506cd98
      HVMG2: ami-0a7c483d527806435
    eu-west-2:
      HVM64: ami-f976839e
      HVMG2: NOT_SUPPORTED
    eu-west-3:
      HVM64: ami-00dd995cb6f0a5219
      HVMG2: NOT_SUPPORTED
    eu-central-1:
      HVM64: ami-0233214e13e500f77
      HVMG2: ami-06223d46a6d0661c7
    eu-south-1:
      HVM64: ami-081e7f992eee19465
      HVMG2: NOT_SUPPORTED
    ap-northeast-1:
      HVM64: ami-06cd52961ce9f0d85
      HVMG2: ami-053cdd503598e4a9d
    ap-northeast-2:
      HVM64: ami-0a10b2721688ce9d2
      HVMG2: NOT_SUPPORTED
    ap-northeast-3:
      HVM64: ami-0d98120a9fb693f07
      HVMG2: NOT_SUPPORTED
    ap-southeast-1:
      HVM64: ami-08569b978cc4dfa10
      HVMG2: ami-0be9df32ae9f92309
    ap-southeast-2:
      HVM64: ami-09b42976632b27e9b
      HVMG2: ami-0a9ce9fecc3d1daf8
    ap-south-1:
      HVM64: ami-0912f71e06545ad88
      HVMG2: ami-097b15e89dbdcfcf4
    us-east-2:
      HVM64: ami-0b59bfac6be064b78
      HVMG2: NOT_SUPPORTED
    ca-central-1:
      HVM64: ami-0b18956f
      HVMG2: NOT_SUPPORTED
    sa-east-1:
      HVM64: ami-07b14488da8ea02a0
      HVMG2: NOT_SUPPORTED
    cn-north-1:
      HVM64: ami-0a4eaf6c4454eda75
      HVMG2: NOT_SUPPORTED
    cn-northwest-1:
      HVM64: ami-6b6a7d09
      HVMG2: NOT_SUPPORTED
Resources:
  EFSMountTargetVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VPCCidr
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: EFSMountTargetVPC
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: EFSMountTargetVPCInternetGateway
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId:
        Ref: EFSMountTargetVPC
      InternetGatewayId:
        Ref: InternetGateway
  IGWRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: EFSMountTargetVPC
      Tags:
        - Key: Name
          Value: EFSMountTargetVPC-IGWRoute
  IGWRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        Ref: IGWRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: InternetGateway
  IGWSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: EFSMountTargetSubnet
      RouteTableId:
        Ref: IGWRouteTable
  EFSMountTargetSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref EFSMountTargetVPC
      CidrBlock: !Select
        - 0
        - !Cidr
          - !Ref VPCCidr
          - 6
          - 5
      Tags:
        - Key: Name
          Value: EFSMountTargetSubnet
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow all outbound traffic including the mount target Security group on the NFS port.
      VpcId: !Ref EFSMountTargetVPC
      SecurityGroupEgress:
        - IpProtocol: "-1"
          FromPort: 0
          ToPort: 0
          CidrIp: 0.0.0.0/0
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: InstanceSecurityGroup
  CloudWatchPutMetricsRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonElasticFileSystemsUtils
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
  CloudWatchPutMetricsRolePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: CloudWatch_PutMetricData
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: CloudWatchPutMetricData
            Effect: Allow
            Action:
              - cloudwatch:PutMetricData
            Resource:
              - "*"
      Roles:
        - Ref: CloudWatchPutMetricsRole
  CloudWatchPutMetricsInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
        - Ref: CloudWatchPutMetricsRole
  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap [AWSRegionArch2AMI, !Ref 'AWS::Region', !FindInMap [AWSInstanceType2Arch, !Ref InstanceType, Arch]]
      InstanceType: !Ref InstanceType
      IamInstanceProfile:
        Ref: CloudWatchPutMetricsInstanceProfile
      Tags:
        - Key: Name
          Value: EFS-Ec2Instance
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: "0"
          GroupSet:
            - Ref: "InstanceSecurityGroup"
          SubnetId:
            Ref: "EFSMountTargetSubnet"
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum install -y nfs-utils amazon-efs-utils
          wget https://bootstrap.pypa.io/get-pip.py -O /tmp/get-pip.py
          /usr/bin/env python3 /tmp/get-pip.py
          /usr/local/bin/pip3 install botocore
          /opt/aws/bin/cfn-init -v --stack ${AWS::StackId} --resource Ec2Instance --region  ${AWS::Region} --configsets default
    Metadata:
      AWS::CloudFormation::Init:
        configSets:
          default:
            - setup
            - mount
        setup:
          files:
            "/etc/amazon/efs/efs-utils.conf":
              mode: '000644'
              content: !Sub |
                  #
                  # Copyright 2017-2018 Amazon.com, Inc. and its affiliates. All Rights Reserved.
                  #
                  # Licensed under the MIT License. See the LICENSE accompanying this file
                  # for the specific language governing permissions and limitations under
                  # the License.
                  #

                  [DEFAULT]
                  logging_level = INFO
                  logging_max_bytes = 1048576
                  logging_file_count = 10
                  # mode for /var/run/efs and subdirectories in octal
                  state_file_dir_mode = 750

                  [mount]
                  dns_name_format = {az}.{fs_id}.efs.{region}.{dns_name_suffix}
                  dns_name_suffix = amazonaws.com
                  #The region of the file system when mounting from on-premises or cross region.
                  #region = us-east-1
                  stunnel_debug_enabled = false
                  #Uncomment the below option to save all stunnel logs for a file system to the same file
                  #stunnel_logs_file = /var/log/amazon/efs/{fs_id}.stunnel.log
                  stunnel_cafile = /etc/amazon/efs/efs-utils.crt

                  # Validate the certificate hostname on mount. This option is not supported by certain stunnel versions.
                  stunnel_check_cert_hostname = true

                  # Use OCSP to check certificate validity. This option is not supported by certain stunnel versions.
                  stunnel_check_cert_validity = false

                  # Define the port range that the TLS tunnel will choose from
                  port_range_lower_bound = 20049
                  port_range_upper_bound = 20449

                  [mount.cn-north-1]
                  dns_name_suffix = amazonaws.com.cn


                  [mount.cn-northwest-1]
                  dns_name_suffix = amazonaws.com.cn


                  [mount.us-iso-east-1]
                  dns_name_suffix = c2s.ic.gov
                  stunnel_cafile = /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem

                  [mount.us-isob-east-1]
                  dns_name_suffix = sc2s.sgov.gov
                  stunnel_cafile = /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem

                  [mount-watchdog]
                  enabled = true
                  poll_interval_sec = 1
                  unmount_grace_period_sec = 30

                  # Set client auth/access point certificate renewal rate. Minimum value is 1 minute.
                  tls_cert_renewal_interval_min = 60

                  [cloudwatch-log]
                  enabled = true
                  log_group_name = ${EFSLogGroup}

                  # Possible values are : 1, 3, 5, 7, 14, 30, 60, 90, 120, 150, 180, 365, 400, 545, 731, 1827, and 3653
                  # Comment this config to prevent log deletion
                  retention_in_days = 14
          commands:
            01_createdir:
              command: !Sub "mkdir -p ${MountPoint}"
        mount:
          commands:
            01_mount:
              command: !Sub
                - 'mount -t efs ${FileSystemId}:/ ${MountPoint}'
                - {MountPoint: !Ref MountPoint, FileSystemId: !Ref FileSystem}
            02_permissions:
              command: !Sub
                - "chown ec2-user:ec2-user ${MountPoint}"
                - {MountPoint: !Ref MountPoint}
            03_fstab:
              command: !Sub
                - echo "${FileSystemId}:/  ${MountPoint} efs _netdev,noresvport,tls,iam  0 0 " >> /etc/fstab
                - {MountPoint: !Ref MountPoint, FileSystemId: !Ref FileSystem}
  EFSMountTargetSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow inbound access for the TCP protocol on the NFS port from all EC2 instances on which you want to mount the file system.
      VpcId: !Ref EFSMountTargetVPC
      SecurityGroupIngress:
        - IpProtocol: "tcp"
          FromPort: 2049
          ToPort: 2049
          SourceSecurityGroupId: !Ref InstanceSecurityGroup
      SecurityGroupEgress:
        - IpProtocol: "-1"
          FromPort: 0
          ToPort: 0
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: EFSMountTargetSecurityGroup
  FileSystem:
    Type: 'AWS::EFS::FileSystem'
    Properties:
      BackupPolicy:
        Status: ENABLED
      PerformanceMode: generalPurpose
      ThroughputMode: provisioned
      ProvisionedThroughputInMibps: 10
      Encrypted: true
      FileSystemTags:
        - Key: Name
          Value: !Ref AWS::StackName
  EFSMountTarget:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref FileSystem
      SubnetId: !Ref EFSMountTargetSubnet
      SecurityGroups:
        - !Ref EFSMountTargetSecurityGroup
  JobIAMRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - backup.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSBackupServiceRolePolicyForBackup
        - arn:aws:iam::aws:policy/service-role/AWSBackupServiceRolePolicyForRestores
  PercentIOLimitAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmDescription: "efs:alarm:percent_io_limit:2020-04-01"
      ActionsEnabled: false
      MetricName: PercentIOLimit
      Namespace: AWS/EFS
      Period: 60
      Statistic: Average
      EvaluationPeriods: 5
      DatapointsToAlarm: 3
      Threshold: !Ref AlarmIOThreshold
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FileSystemId
          Value: !Ref FileSystem
      TreatMissingData: missing
  EFSLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/${AWS::StackName}/aws/efs/utils'

  MountFailureMetric:
    Type: AWS::Logs::MetricFilter
    Properties:
      FilterPattern: "Mount failed"
      LogGroupName: !Ref EFSLogGroup
      MetricTransformations:
        -
          MetricValue: "1"
          DefaultValue: 0.0
          MetricNamespace: "EFSMounts"
          MetricName: !Sub
            - 'MountFailures-${FileSystemId}-${EC2ID}'
            - {EC2ID: !Ref Ec2Instance, FileSystemId: !Ref FileSystem}
  MountFailureAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmDescription: "efs:alarm:ec2-mount-failure:2020-04-01"
      ActionsEnabled: false
      MetricName: !Sub
        - 'MountFailures-${FileSystemId}-${EC2ID}'
        - {EC2ID: !Ref Ec2Instance, FileSystemId: !Ref FileSystem}
      Namespace: EFSMounts
      Statistic: Maximum
      Period: 60
      EvaluationPeriods: 5
      DatapointsToAlarm: 1
      Threshold: 0
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      Unit: None
  ClientConnectionsAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmDescription: "efs:alarm:client_connections:2020-04-01"
      ActionsEnabled: false
      MetricName: ClientConnections
      Namespace: AWS/EFS
      Period: 60
      Statistic: Average
      EvaluationPeriods: 3
      DatapointsToAlarm: 1
      ComparisonOperator: LessThanThreshold
      Threshold: !Ref AlarmClientConnectionsThreshold
      Dimensions:
        - Name: FileSystemId
          Value: !Ref FileSystem
      TreatMissingData: breaching
  BackupVaultSource:
    Type: AWS::Backup::BackupVault
    Properties:
      BackupVaultName: !Join
        - "-"
        - - "backup-vault-source"
          - !Select
            - 0
            - !Split
              - "-"
              - !Select
                - 2
                - !Split
                  - "/"
                  - !Ref "AWS::StackId"
  BackupVaultDestination:
    Type: AWS::Backup::BackupVault
    Properties:
      BackupVaultName: !Join
        - "-"
        - - "backup-vault-destination"
          - !Select
            - 0
            - !Split
              - "-"
              - !Select
                - 2
                - !Split
                  - "/"
                  - !Ref "AWS::StackId"
