#
# Copyright 2021 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this
# software and associated documentation files (the "Software"), to deal in the Software
# without restriction, including without limitation the rights to use, copy, modify,
# merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
# PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
---
AWSTemplateFormatVersion: 2010-09-09
Description: Test stack for ElastiCache Redis replication group with cluster mode enabled in a multi AZ deployment
Outputs:
  ReplicationGroupId:
    Description: The ID of the Replication group
    Value: !Ref ElastiCacheReplicationGroup
  SNSTopicName:
    Description: SNS Topic Name
    Value: !Ref SNSTopic
  RoleApproveChangeCacheParameterGroupArn:
    Description: ARN of RoleApproveChangeCacheParameterBucket
    Value: !GetAtt RoleApproveChangeCacheParameterBucket.Arn
Parameters:
  EngineVersion:
    Description: The version number of the cache engine to be used for the clusters in this replication group
    Type: String
    Default: 6.x
  ParameterGroupName:
    Description: The name of the parameter group to associate with this replication group
    Type: String
    Default: default.redis6.x.cluster.on
  NodeType:
    Description: The compute and memory capacity of the nodes in the node group (shard)
    Type: String
    Default: cache.t3.micro
  VpcCIDR:
    Description: IP range in CIDR notation for the VPC
    Type: String
    Default: 10.0.0.0/22
  PrivateSubnetCIDR1:
    Description: IP range in CIDR notation for the ElastiCache subnet in AZ 1
    Type: String
    Default: 10.0.0.0/24
  PrivateSubnetCIDR2:
    Description: IP range in CIDR notation for the ElastiCache subnet in AZ 2
    Type: String
    Default: 10.0.1.0/24
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsSupport: true
      EnableDnsHostnames: true

  PrivateSubnetAZ1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 0, !GetAZs "" ]
      CidrBlock: !Ref PrivateSubnetCIDR1
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: 'Private subnet for ElastiCache Redis (AZ1)'
  PrivateSubnetAZ2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 1, !GetAZs "" ]
      CidrBlock: !Ref PrivateSubnetCIDR2
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: 'Private subnet for ElastiCache Redis (AZ2)'

  PrivateSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: 'Private security group for ElastiCache'
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: "-1"
          CidrIp: !Ref PrivateSubnetCIDR1
        - IpProtocol: "-1"
          CidrIp: !Ref PrivateSubnetCIDR2
      SecurityGroupEgress:
        - IpProtocol: "-1"
          CidrIp: !Ref PrivateSubnetCIDR1
        - IpProtocol: "-1"
          CidrIp: !Ref PrivateSubnetCIDR2

  ElastiCacheSubnetGroup:
    Type: AWS::ElastiCache::SubnetGroup
    Properties:
      Description: "ElastiCache subnet group"
      SubnetIds:
        - !Ref PrivateSubnetAZ1
        - !Ref PrivateSubnetAZ2

  ElastiCacheReplicationGroup:
    Type: AWS::ElastiCache::ReplicationGroup
    UpdatePolicy:
      UseOnlineResharding: true
    Properties:
      AtRestEncryptionEnabled: true
      AutomaticFailoverEnabled: true
      CacheNodeType: !Ref NodeType
      CacheParameterGroupName: !Ref ParameterGroupName
      CacheSubnetGroupName: !Ref ElastiCacheSubnetGroup
      Engine: 'redis'
      EngineVersion: !Ref EngineVersion
      KmsKeyId: !Ref KmsKey
      MultiAZEnabled: true
      NumNodeGroups: 2
      ReplicasPerNodeGroup: 1
      ReplicationGroupDescription: 'ElastiCache Redis with cluster mode enabled in multi AZ deployment'
      ReplicationGroupId: !Join [ "-", [ "redis-cluster-multi-az", !Select [ 0, !Split [ "-", !Select [ 2, !Split [ "/", !Ref "AWS::StackId" ] ] ] ] ] ]
      SecurityGroupIds:
        - !Ref PrivateSecurityGroup
      TransitEncryptionEnabled: true

  KmsKey:
    Type: AWS::KMS::Key
    Properties:
      KeyPolicy:
        Version: '2012-10-17'
        Id: !Join [ "-", [ "kms-key-policy", !Select [ 0, !Split [ "-", !Select [ 2, !Split [ "/", !Ref "AWS::StackId" ] ] ] ] ] ]
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: kms:*
            Resource: "*"

  SNSTopic:
    Type: "AWS::SNS::Topic"
    Properties:
      KmsMasterKeyId: !Ref KmsKey

  SNSTopicPolicy:
    Type: "AWS::SNS::TopicPolicy"
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Id: SNSTopicPolicy
        Statement:
          - Sid: SNSTopicPolicyStatement
            Effect: Allow
            Principal:
              Service:
                - cloudwatch.amazonaws.com
            Action:
              - SNS:Publish
            Resource: !Ref SNSTopic
            Condition:
              StringEquals:
                AWS:SourceAccount: !Ref "AWS::AccountId"
      Topics:
        - !Ref SNSTopic

  RoleApproveChangeCacheParameterBucket:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Ref "AWS::AccountId"
            Action:
              - sts:AssumeRole

  PolicyApproveChangeCacheParameterBucket:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: DigitoRestoreFromBackupAssumePolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Resource: "*"
            Action:
              - ssm:SendAutomationSignal
      Roles:
        - Ref: RoleApproveChangeCacheParameterBucket
