#
# Copyright 2021 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this
# software and associated documentation files (the "Software"), to deal in the Software
# without restriction, including without limitation the rights to use, copy, modify,
# merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
# PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
---
AWSTemplateFormatVersion: 2010-09-09
Description: Test stack for ElastiCache Redis replication group with cluster mode disabled in a multi AZ deployment
Outputs:
  ReplicationGroupId:
    Description: The ID of the Replication group
    Value: !Ref ElastiCacheReplicationGroup
Parameters:
  EngineVersion:
    Description: The version number of the cache engine to be used for the clusters in this replication group
    Type: String
    Default: 6.x
  ParameterGroupName:
    Description: The name of the parameter group to associate with this replication group
    Type: String
    Default: default.redis6.x
  NodeType:
    Description: The compute and memory capacity of the nodes in the node group (shard)
    Type: String
    Default: cache.t2.small
  NumCacheClusters:
    Description: The number of clusters this replication group initially has. The maximum permitted value for NumCacheClusters is 6 (1 primary plus 5 replicas).
    Type: Number
    Default: 3
  VpcCIDR:
    Description: IP range in CIDR notation for the VPC
    Type: String
    Default: 10.0.0.0/22
  PrivateSubnetCIDR1:
    Description: IP range in CIDR notation for the ElastiCache subnet in AZ 1
    Type: String
    Default: 10.0.0.0/24
  PrivateSubnetCIDR2:
    Description: IP range in CIDR notation for the ElastiCache subnet in AZ 2
    Type: String
    Default: 10.0.1.0/24
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsSupport: true
      EnableDnsHostnames: true

  PrivateSubnetAZ1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 0, !GetAZs "" ]
      CidrBlock: !Ref PrivateSubnetCIDR1
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: 'Private subnet for ElastiCache Redis (AZ1)'
  PrivateSubnetAZ2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 1, !GetAZs "" ]
      CidrBlock: !Ref PrivateSubnetCIDR2
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: 'Private subnet for ElastiCache Redis (AZ2)'

  PrivateSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: 'Private security group for ElastiCache'
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: "-1"
          CidrIp: !Ref PrivateSubnetCIDR1
        - IpProtocol: "-1"
          CidrIp: !Ref PrivateSubnetCIDR2
      SecurityGroupEgress:
        - IpProtocol: "-1"
          CidrIp: !Ref PrivateSubnetCIDR1
        - IpProtocol: "-1"
          CidrIp: !Ref PrivateSubnetCIDR2

  ElastiCacheSubnetGroup:
    Type: AWS::ElastiCache::SubnetGroup
    Properties:
      Description: "ElastiCache subnet group"
      SubnetIds:
        - !Ref PrivateSubnetAZ1
        - !Ref PrivateSubnetAZ2

  ElastiCacheReplicationGroup:
    Type: AWS::ElastiCache::ReplicationGroup
    Properties:
      AtRestEncryptionEnabled: true
      AutomaticFailoverEnabled: true
      CacheNodeType: !Ref NodeType
      CacheParameterGroupName: !Ref ParameterGroupName
      CacheSubnetGroupName: !Ref ElastiCacheSubnetGroup
      Engine: 'redis'
      EngineVersion: !Ref EngineVersion
      KmsKeyId: !Ref KmsKey
      MultiAZEnabled: true
      NumCacheClusters: !Ref NumCacheClusters
      ReplicationGroupDescription: 'ElastiCache Redis with cluster mode disabled in multi AZ deployment'
      ReplicationGroupId: !Join [ "-", [ "redis-non-cluster-multi-az", !Select [ 0, !Split [ "-", !Select [ 2, !Split [ "/", !Ref "AWS::StackId" ] ] ] ] ] ]
      SecurityGroupIds:
        - !Ref PrivateSecurityGroup
      TransitEncryptionEnabled: true

  KmsKey:
    Type: AWS::KMS::Key
    Properties:
      KeyPolicy:
        Version: '2012-10-17'
        Id: !Join [ "-", [ "kms-key-policy", !Select [ 0, !Split [ "-", !Select [ 2, !Split [ "/", !Ref "AWS::StackId" ] ] ] ] ] ]
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: kms:*
            Resource: "*"
