#
# Copyright 2021 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this
# software and associated documentation files (the "Software"), to deal in the Software
# without restriction, including without limitation the rights to use, copy, modify,
# merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
# PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
---
AWSTemplateFormatVersion: 2010-09-09
Description: Test stack for ElastiCache Cluster for Redis in a single AZ deployment
Outputs:
  ClusterId:
    Description: The ID of the Redis cluster
    Value: !Ref ElastiCacheCluster
Parameters:
  AZMode:
    Description: Specifies whether the nodes in this cluster are created in a single Availability Zone or created across multiple Availability Zones
    Type: String
    Default: single-az
  EngineVersion:
    Description: The version number of the cache engine to be used for the cluster
    Type: String
    Default: 6.x
  ParameterGroupName:
    Description: The name of the parameter group to associate with this cluster
    Type: String
    Default: default.redis6.x
  NodeType:
    Description: The compute and memory capacity of the cluster nodes
    Type: String
    Default: cache.t2.medium
  VpcCIDR:
    Description: IP range in CIDR notation for the VPC
    Type: String
    Default: 10.0.0.0/22
  PrivateSubnetCIDR1:
    Description: IP range in CIDR notation for the ElastiCache subnet in AZ 1
    Type: String
    Default: 10.0.0.0/24
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsSupport: true
      EnableDnsHostnames: true

  PrivateSubnetAZ1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 0, !GetAZs "" ]
      CidrBlock: !Ref PrivateSubnetCIDR1
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: 'Private subnet for ElastiCache Memcached (AZ1)'

  PrivateSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: 'Private security group for ElastiCache'
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: "-1"
          CidrIp: !Ref PrivateSubnetCIDR1
      SecurityGroupEgress:
        - IpProtocol: "-1"
          CidrIp: !Ref PrivateSubnetCIDR1

  ElastiCacheSubnetGroup:
    Type: AWS::ElastiCache::SubnetGroup
    Properties:
      Description: 'ElastiCache subnet group'
      SubnetIds:
        - !Ref PrivateSubnetAZ1

  ElastiCacheCluster:
    Type: AWS::ElastiCache::CacheCluster
    Properties:
      AZMode: !Ref AZMode
      CacheNodeType: !Ref NodeType
      CacheParameterGroupName: !Ref ParameterGroupName
      CacheSubnetGroupName: !Ref ElastiCacheSubnetGroup
      Engine: 'redis'
      EngineVersion: !Ref EngineVersion
      NumCacheNodes: 1
      PreferredAvailabilityZone: !Select [ 0, !GetAZs "" ]
      VpcSecurityGroupIds:
        - !Ref PrivateSecurityGroup
