#
# Copyright 2021 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this
# software and associated documentation files (the "Software"), to deal in the Software
# without restriction, including without limitation the rights to use, copy, modify,
# merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
# PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
---
AWSTemplateFormatVersion: 2010-09-09
Description: Test stack for HTTP and WS API GW
Outputs:
  WsApiGwId:
    Description: The ID of the Websockets API Gateway
    Value: !Ref WsApi
  WsDefaultDeploymentId:
    Description: The ID of the default deployment of Websockets API Gateway
    Value: !Ref WsDefaultDeployment
  WsStageName:
    Description: The stage name of Websockets API Gateway
    Value: !Ref WsStage
  WsStageNameThrottled:
    Description: The stage name of Websockets API Gateway with throttling enabled
    Value: !Ref WsStageThrottled
  WsApiThrottledEndpoint:
    Description: The URL of the HTTP API Gateway
    Value: !Sub "wss://${WsApi}.execute-api.${AWS::Region}.amazonaws.com/${WsStageThrottled}"
  WsStageNameAutoDeploy:
    Description: The stage name of Websockets API Gateway with AutoDeploy enabled
    Value: !Ref WsStageAutoDeploy
  Ws4XXErrorAlarmName:
    Description: WS API Gateway Alarm based on ClientError metric
    Value: !Ref Ws4XXErrorAlarm
  HttpApiGwId:
    Description: The ID of the HTTP API Gateway
    Value: !Ref HttpApi
  HttpDefaultDeploymentId:
    Description: The ID of the default deployment of HTTP API Gateway
    Value: !Ref HttpDefaultDeployment
  HttpStageName:
    Description: The stage name of HTTP API Gateway
    Value: !Ref HttpStage
  HttpStageNameThrottled:
    Description: The stage name of HTTP API Gateway with throttling enabled
    Value: !Ref HttpStageThrottled
  HttpApiThrottledEndpoint:
    Description: The URL of the HTTP API Gateway
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/${HttpStageThrottled}/test_default"
  HttpStageNameAutoDeploy:
    Description: The stage name of HTTP API Gateway with AutoDeploy enabled
    Value: !Ref HttpStageAutoDeploy
  Http4XXErrorAlarmName:
    Description: HTTP API Gateway Alarm based on 4xx metric
    Value: !Ref Http4XXErrorAlarm
Parameters:
  LambdaCode:
    Type: String
    Description: Code to upload to Lambda
    Default: >
      def handler(event, context):
        print('hello from lambda')
Resources:
  WsApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: !Join
        - "-"
        - - "WsApiGateway-Digito"
          - !Ref "AWS::Region"
          - !Ref "AWS::AccountId"
          - !Select
            - 0
            - !Split
              - "-"
              - !Select
                - 2
                - !Split
                  - "/"
                  - !Ref "AWS::StackId"
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: "$request.body.action"

  WsConnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WsApi
      RouteKey: $connect
      RouteResponseSelectionExpression: '$default'
      AuthorizationType: NONE
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref WsConnectIntegration
  WsConnectIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WsApi
      Description: Connect Integration
      IntegrationType: MOCK
      TemplateSelectionExpression: '200'
      RequestTemplates:
        "200": '{"statusCode" : 200}'
  WsConnectIntegrationResponse:
    Type: AWS::ApiGatewayV2::IntegrationResponse
    Properties:
      ApiId: !Ref WsApi
      IntegrationId: !Ref WsConnectIntegration
      IntegrationResponseKey: '$default'
      TemplateSelectionExpression: '200'
      ResponseTemplates:
        "200": '{"statusCode" : 200}'
  WsConnectRouteResponse:
    Type: AWS::ApiGatewayV2::RouteResponse
    Properties:
      RouteId: !Ref WsConnectRoute
      ApiId: !Ref WsApi
      RouteResponseKey: $default

  WsDisconnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WsApi
      RouteKey: $disconnect
      RouteResponseSelectionExpression: '$default'
      AuthorizationType: NONE
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref WsDisconnectIntegration
  WsDisconnectIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WsApi
      Description: Disconnect Integration
      IntegrationType: MOCK
      TemplateSelectionExpression: '200'
      RequestTemplates:
        "200": '{"statusCode" : 200}'
  WsDisconnectIntegrationResponse:
    Type: AWS::ApiGatewayV2::IntegrationResponse
    Properties:
      ApiId: !Ref WsApi
      IntegrationId: !Ref WsDisconnectIntegration
      IntegrationResponseKey: '$default'
      TemplateSelectionExpression: '200'
      ResponseTemplates:
        "200": '{"statusCode" : 200}'
  WsDisconnectRouteResponse:
    Type: AWS::ApiGatewayV2::RouteResponse
    Properties:
      RouteId: !Ref WsDisconnectRoute
      ApiId: !Ref WsApi
      RouteResponseKey: $default

  WsDefaultRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WsApi
      RouteKey: $default
      RouteResponseSelectionExpression: '$default'
      AuthorizationType: NONE
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref WsDefaultIntegration
  WsDefaultIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WsApi
      Description: Default Integration
      IntegrationType: MOCK
      TemplateSelectionExpression: '200'
      RequestTemplates:
        "200": '{"statusCode" : 200}'
  WsDefaultIntegrationResponse:
    Type: AWS::ApiGatewayV2::IntegrationResponse
    Properties:
      ApiId: !Ref WsApi
      IntegrationId: !Ref WsDefaultIntegration
      IntegrationResponseKey: '$default'
      TemplateSelectionExpression: '200'
      ResponseTemplates:
        "200": '{"statusCode" : 200}'
  WsDefaultRouteResponse:
    Type: AWS::ApiGatewayV2::RouteResponse
    Properties:
      RouteId: !Ref WsDefaultRoute
      ApiId: !Ref WsApi
      RouteResponseKey: $default
  WsDefaultDeployment:
    DependsOn: WsDefaultRoute
    Type: AWS::ApiGatewayV2::Deployment
    Properties:
      ApiId: !Ref WsApi
      Description: Default deployment
  WsStage:
    DependsOn: WsDefaultDeployment
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref WsApi
      DeploymentId: !Ref WsDefaultDeployment
      StageName: !Join
        - "-"
        - - "WsApiGateway-Digito-test"
          - !Ref "AWS::Region"
          - !Ref "AWS::AccountId"
          - !Select
            - 0
            - !Split
              - "-"
              - !Select
                - 2
                - !Split
                  - "/"
                  - !Ref "AWS::StackId"
  WsStageAutoDeploy:
    DependsOn: WsDefaultDeployment
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref WsApi
      DeploymentId: !Ref WsDefaultDeployment
      AutoDeploy: true
      StageName: !Join
        - "-"
        - - "WsApiGateway-Digito-test-autodeploy"
          - !Ref "AWS::Region"
          - !Ref "AWS::AccountId"
          - !Select
            - 0
            - !Split
              - "-"
              - !Select
                - 2
                - !Split
                  - "/"
                  - !Ref "AWS::StackId"
  WsStageThrottled:
    DependsOn: WsDefaultDeployment
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref WsApi
      DeploymentId: !Ref WsDefaultDeployment
      DefaultRouteSettings:
        ThrottlingBurstLimit: 100
        ThrottlingRateLimit: 100.0
      RouteSettings:
        "$default":
          ThrottlingBurstLimit: 100
          ThrottlingRateLimit: 100.0
      StageName: !Join
        - "-"
        - - "WsApiGateway-Digito-test-throttled"
          - !Ref "AWS::Region"
          - !Ref "AWS::AccountId"
          - !Select
            - 0
            - !Split
              - "-"
              - !Select
                - 2
                - !Split
                  - "/"
                  - !Ref "AWS::StackId"
  Ws4XXErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: false
      AlarmDescription: 'WS Api Gateway 4xx Errors'
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: ApiId
          Value: !Ref WsApi
        - Name: Stage
          Value: !Ref WsStageThrottled
      EvaluationPeriods: 5
      DatapointsToAlarm: 3
      MetricName: ClientError
      Namespace: AWS/ApiGateway
      Period: 60
      ExtendedStatistic: p20
      Threshold: 0
      TreatMissingData: notBreaching

  HttpApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: !Join
        - "-"
        - - "HttpApiGateway-Digito"
          - !Ref "AWS::Region"
          - !Ref "AWS::AccountId"
          - !Select
            - 0
            - !Split
              - "-"
              - !Select
                - 2
                - !Split
                  - "/"
                  - !Ref "AWS::StackId"
      ProtocolType: HTTP
  HttpRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: "POST /test"
      AuthorizationType: NONE
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref HttpDefaultIntegration
  HttpDefaultRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: "$default"
      AuthorizationType: NONE
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref HttpDefaultIntegration
  HttpDefaultIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref HttpApi
      Description: Default Integration
      IntegrationMethod: POST
      IntegrationType: AWS_PROXY
      IntegrationUri: !Join
        - ''
        - - 'arn:'
          - !Ref 'AWS::Partition'
          - ':apigateway:'
          - !Ref 'AWS::Region'
          - ':lambda:path/2015-03-31/functions/'
          - !GetAtt LambdaFunction.Arn
          - /invocations
      PayloadFormatVersion: "2.0"
  HttpDefaultDeployment:
    DependsOn: HttpRoute
    Type: AWS::ApiGatewayV2::Deployment
    Properties:
      ApiId: !Ref HttpApi
      Description: Default deployment
  HttpStage:
    DependsOn: HttpDefaultDeployment
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref HttpApi
      DeploymentId: !Ref HttpDefaultDeployment
      StageName: !Join
        - "-"
        - - "HttpApiGateway-Digito-test"
          - !Ref "AWS::Region"
          - !Ref "AWS::AccountId"
          - !Select
            - 0
            - !Split
              - "-"
              - !Select
                - 2
                - !Split
                  - "/"
                  - !Ref "AWS::StackId"
  HttpStageAutoDeploy:
    DependsOn: HttpDefaultDeployment
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref HttpApi
      DeploymentId: !Ref HttpDefaultDeployment
      AutoDeploy: true
      StageName: !Join
        - "-"
        - - "HttpApiGateway-Digito-test-autodeploy"
          - !Ref "AWS::Region"
          - !Ref "AWS::AccountId"
          - !Select
            - 0
            - !Split
              - "-"
              - !Select
                - 2
                - !Split
                  - "/"
                  - !Ref "AWS::StackId"
  HttpStageThrottled:
    DependsOn: HttpDefaultDeployment
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref HttpApi
      DeploymentId: !Ref HttpDefaultDeployment
      DefaultRouteSettings:
        ThrottlingBurstLimit: 100
        ThrottlingRateLimit: 100.0
      RouteSettings:
        "POST /test":
          ThrottlingBurstLimit: 100
          ThrottlingRateLimit: 100.0
      StageName: !Join
        - "-"
        - - "HttpApiGateway-Digito-test-throttled"
          - !Ref "AWS::Region"
          - !Ref "AWS::AccountId"
          - !Select
            - 0
            - !Split
              - "-"
              - !Select
                - 2
                - !Split
                  - "/"
                  - !Ref "AWS::StackId"
  Http4XXErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: false
      AlarmDescription: 'HTTP Api Gateway 4xx Errors'
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: ApiId
          Value: !Ref HttpApi
        - Name: Stage
          Value: !Ref HttpStageThrottled
      EvaluationPeriods: 5
      DatapointsToAlarm: 3
      MetricName: 4xx
      Namespace: AWS/ApiGateway
      Period: 60
      ExtendedStatistic: p20
      Threshold: 0
      TreatMissingData: notBreaching
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: !Ref LambdaCode
      Handler: index.handler
      Role: !GetAtt LambdaRole.Arn
      Runtime: python3.8
      Timeout: 60
      ReservedConcurrentExecutions: 1
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Description: Lambda Role
  HttpApiGWPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt LambdaFunction.Arn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceAccount: !Ref 'AWS::AccountId'
      SourceArn: !Join
        - ''
        - - 'arn:aws:execute-api:'
          - !Ref 'AWS::Region'
          - ':'
          - !Ref 'AWS::AccountId'
          - ':'
          - !Ref HttpApi
          - /*/*/test_default