#
# Copyright 2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this
# software and associated documentation files (the "Software"), to deal in the Software
# without restriction, including without limitation the rights to use, copy, modify,
# merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
# PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
---
AWSTemplateFormatVersion: 2010-09-09
Description: Test stack for network load-balancer
Outputs:
  NetworkELBArn:
    Description: Network Load Balancer ARN
    Value: !Ref  NetworkELB
  NetworkELBUrl:
    Description: The Network Elastic Load Balancer DNS Name
    Value: !GetAtt NetworkELB.DNSName
  NetworkELBFullName:
    Description: The Network Elastic Load Balancer Key For Alarm Setup
    Value: !GetAtt NetworkELB.LoadBalancerFullName
  TargetGroup:
    Description: TargetGroup name
    Value: !GetAtt NLBTargetGroup.TargetGroupFullName
  TargetGroupArn:
    Description: TargetGroup Arn
    Value: !Ref NLBTargetGroup
Parameters:
  VPC:
    Type: String
    Description: VPC ID
  VPCCidr:
    Type: String
    Description: VPC Cidr
  Subnet1:
    Type: String
    Description: Subnet ID
  EC2Subnet:
    Type: String
    Default: ""
  InstanceType:
    Type: String
    Default: t3.small
  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'
  ListenPort:
    Type: String
    Default: 80
  SSLCertificateBody:
    Type: String
    Default: |
      -----BEGIN CERTIFICATE-----
      MIIDBjCCAe4CCQC/gsk8A/TgUjANBgkqhkiG9w0BAQsFADBFMQswCQYDVQQGEwJV
      UzEYMBYGA1UECgwPX0RldmVsb3BtZW50IENBMRwwGgYDVQQDDBMqLmVsYi5hbWF6
      b25hd3MuY29tMB4XDTIxMDgxMDE2MDQ0N1oXDTIyMDgxMDE2MDQ0N1owRTELMAkG
      A1UEBhMCVVMxGDAWBgNVBAoMD19EZXZlbG9wbWVudCBDQTEcMBoGA1UEAwwTKi5l
      bGIuYW1hem9uYXdzLmNvbTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEB
      AM8nrJDtLHcTFvmsi13BWZKuoFRE1/zy1to2RNXYQZSKOmD2Z5tNjRcKwVRapFG0
      u6TaXZWquO4h7ERxGkgInufEFAt4BLr3AbXfZ2DGNmMcjint+SaoDvsfmjDfpJV5
      Dfk7ht6xJkDjwSNAaHSmQEAx2sevANfO9hZsc7bQzFQetwoSVnNrCedckTQcpcbz
      joNNRMY74u9cOvG7QAboqA9/K3iJv3buStZ+krGT2qpK1W/AliW8erS1jz9C4Hav
      F6vur5vGHglmGdRULNb1vvC1Qj6ohgrCD1dkiTj8ZQRkTqrGFzZjqL8lAuyslNNd
      OLvnKvKp1FVW/b68dSQzKocCAwEAATANBgkqhkiG9w0BAQsFAAOCAQEAZL2jqQgF
      CUG9H5c5D5XhQoM9bMBF8G/iw4btOYSM0DEKzLJFObpPmZvWCH7EMaWNJOKA6Eza
      WPKXplpYTDIiKqa88kptp08cal48hxH9+O4nodlIbGxtRIXC2n2ZwBN0Ysgwo3TL
      HDU2IDgzZuA3gYBhG5u29uhIMJ+TvlfkcSwz8CbjdJc+2/SL7jIOcieMve8zpwLL
      tValKMoOk17B57ODKepyVPX06d+ugqyp+41cWE4azddYHo5xk21T+GjNoSKipPye
      v3rYHWzLv/C9XMY9oJ3woF0jfv1U1YsbX9JvCRz7F56LNde/zbztncdGvaPWZUlI
      10CZ+4fEyDBSUQ==
      -----END CERTIFICATE-----

  SSLCertificatePrivateKey:
    Type: String
    Default: |
      -----BEGIN PRIVATE KEY-----
      MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDPJ6yQ7Sx3Exb5
      rItdwVmSrqBURNf88tbaNkTV2EGUijpg9mebTY0XCsFUWqRRtLuk2l2VqrjuIexE
      cRpICJ7nxBQLeAS69wG132dgxjZjHI4p7fkmqA77H5ow36SVeQ35O4besSZA48Ej
      QGh0pkBAMdrHrwDXzvYWbHO20MxUHrcKElZzawnnXJE0HKXG846DTUTGO+LvXDrx
      u0AG6KgPfyt4ib927krWfpKxk9qqStVvwJYlvHq0tY8/QuB2rxer7q+bxh4JZhnU
      VCzW9b7wtUI+qIYKwg9XZIk4/GUEZE6qxhc2Y6i/JQLsrJTTXTi75yryqdRVVv2+
      vHUkMyqHAgMBAAECggEAejc091gGOMY5ctoaaxjsiL6f9rebGjAHFDyaRfPNVR5s
      LNKS86xARkzhHKxRb6cKYcs3FVrguhWneAWmdMMpRSGIle+cEtYx2yRPsGegpL6v
      HQu6R9U06XGOnbEEP+9okBdPjcjEAdqdEvgn6FJBa9497jtQawI+a6JWbpAnTKS1
      hBZF/kTCf1QUHFu+JuHaRLk7A/hgqGsS1xcFTQV9Cbx9nkJSn0xNxpXvB+/S3xpX
      wp+SnC/KPoKFf7GPhl8W2Z7g0O9MlXZSBaCIdj7NsVrujrK5Br1i7jzhUU9W1qLY
      x59KnoV2vZhVVwaicU/6fxtAPkhp4PfRyOQip/Z9+QKBgQD8iFWxI6pP/QH1tlyQ
      0k5iPsYEebJufU10Tm0kMpOVncqZ7s/ByH9xiMdFPvX5EPObSE19fR4a9ZL9eFZQ
      r/CKietkSAac9UM+CHJaw5EQy7ZAs+PhBeWhJ9vpSF4zKoOu76Sse3DLAHL3j2nE
      9/Lw8KxPtSSYtRLKqInpbkx8PQKBgQDR/9Wy8MbOS1In9y4SnvTeXIoPaIqCk3gM
      N3at8NmpzgZUHermn38fae/BaIiwU4BTD/uPSBofsX2iX9ksiPW/uBKLy/v095gB
      xJ8xchx3N0JeT51Pq+s0OLYsY6+nPAkU/D9Sf61bgosev4XmMKM3KVJ/Yk1e5LkA
      dvNFp0LaEwKBgQDv9pEPASf+WBm7pazyBJVtL980M3wFF9Y41alKQzEQc98oRNBw
      gJfxh5prR3euU5hYjuzreK/ZyE8DwoyqoXS+AG6IXRTDox9hW99mNf2r6xdlBktc
      8SCR8XE7jIPOtPBqk9dz+txkWink6gcEnuPgZaInH6cF4NJZdquOADx3tQKBgQDB
      4OsRK87AQzX0g/bbZjo42UL1etT2PORGkyZU7NpoNTgOjRiEF5ksDYg3DiW0dUMy
      bL0Zyb2kqR+Ou+MrhL8uY+lre8aAod6LM1auNeYmArSZkfNwzQ53xiway2YuhfT0
      lPZ5WjtZEysSFkyu+xSVJudth/pas9xBm5B6LDRCVQKBgH+cse+JpgirMsdyAQ/C
      /idAV7Mt23Xz6LV1FKdXXVxV+HMGy7XVMlcyWrrBJB7ydouqJ2s/apxzn5nglGoX
      UhSDAkFfjNTnyh10qgiBDIcsohicdxMIYGyIMGl8C0Cbzd1bwneu2W3lL3hZD4RK
      KWeMzqbYKrW7t9ud74ONZ4Uu
      -----END PRIVATE KEY-----
Conditions:
  UseCustomSubnet: !Equals [!Ref EC2Subnet, ""]

Resources:
  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Access to the ec2 hosts
      VpcId: !Ref 'VPC'
      SecurityGroupIngress:
        - IpProtocol: icmp
          FromPort: 0
          ToPort: 0
          CidrIp: !Ref VPCCidr
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref VPCCidr
        - IpProtocol: tcp
          FromPort: !Ref ListenPort
          ToPort: !Ref ListenPort
          CidrIp: !Ref VPCCidr
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: !Ref VPCCidr

  NetworkELB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      IpAddressType: ipv4
      LoadBalancerAttributes:
        - Key: deletion_protection.enabled
          Value: "false"
      Scheme: internal
      SubnetMappings:
        - SubnetId: !Ref Subnet1
      Type: network

  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref NLBTargetGroup
      LoadBalancerArn: !Ref NetworkELB
      Port: !Ref ListenPort
      Protocol: TCP
  SSLCertificate:
    Type: AWS::IAM::ServerCertificate
    Properties:
      CertificateBody: !Ref SSLCertificateBody
      PrivateKey: !Ref SSLCertificatePrivateKey
      ServerCertificateName: !Join
        - "-"
        - - "ServerCertificate-Digito"
          - !Ref "AWS::Region"
          - !Ref "AWS::AccountId"
          - !Select
            - 0
            - !Split
              - "-"
              - !Select
                - 2
                - !Split
                  - "/"
                  - !Ref "AWS::StackId"
  Listener443:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref NLBTargetGroup
      LoadBalancerArn: !Ref NetworkELB
      SslPolicy: "ELBSecurityPolicy-2016-08"
      Certificates:
        -
          CertificateArn: !GetAtt SSLCertificate.Arn
      Port: 443
      Protocol: TLS

  NLBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckEnabled: true
      HealthCheckIntervalSeconds: 10
      HealthCheckPort: !Ref ListenPort
      HealthCheckProtocol: TCP
      HealthCheckTimeoutSeconds: 10
      HealthyThresholdCount: 2
      Port: !Ref ListenPort
      Protocol: TCP
      TargetGroupAttributes:
        - Key: stickiness.enabled
          Value: "true"
      Targets:
        - Id:
            Ref: AmazonLinuxInstance
          Port: !Ref ListenPort
      TargetType: instance
      UnhealthyThresholdCount: 2
      VpcId: !Ref VPC

  # Linux Instance with Apache running on Port 80
  AmazonLinuxInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref LatestAmiId
      InstanceInitiatedShutdownBehavior: stop
      InstanceType: !Ref InstanceType
      Monitoring: true
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: '0'
          GroupSet:
            - !Ref EC2SecurityGroup
          SubnetId: !If [UseCustomSubnet, !Ref Subnet1, !Ref EC2Subnet]
      Tenancy: default
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          cd /tmp
          yum update -y
          yum install -y httpd
          yum install -y https://s3.${AWS::Region}.amazonaws.com/amazon-ssm-${AWS::Region}/latest/linux_amd64/amazon-ssm-agent.rpm
          echo "Healthy" > /var/www/html/index.html
          echo "Listen 443" >> /etc/httpd/conf/httpd.conf
          service httpd start
          /opt/aws/bin/cfn-signal \
            -e $? \
            --stack ${AWS::StackName} \
            --resource AmazonLinuxInstance \
            --region ${AWS::Region}
