#
# Copyright 2021 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this
# software and associated documentation files (the "Software"), to deal in the Software
# without restriction, including without limitation the rights to use, copy, modify,
# merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
# PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
---
AWSTemplateFormatVersion: 2010-09-09
Description: Test stack for RDS
Outputs:
  InstanceId:
    Description: Database Instance Id
    Value:
      Ref: DatabaseInstance
  ReplicaInstanceId:
    Description: Replica Database Instance Id
    Value:
      Ref: ReadReplicaDatabaseInstance
  SyntheticAlarmName:
    Description: Database Alarm based on CPUUtilization metric
    Value: !Ref CPUUtilizationAlarm
Parameters:
  DBInstanceClass:
    Description: DB-Instance Class (e.g. db.m1.small, db.r3.8xlarge, etc.)
    Type: String
  AllocatedStorage:
    Description: Specifies the allocated storage size specified in gibibytes
    Type: String
Resources:
  GeneratedSecretString:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Generated RDS Aurora cluster password
      GenerateSecretString:
        SecretStringTemplate: '{"username": "admin"}'
        GenerateStringKey: "password"
        PasswordLength: 16
        ExcludeCharacters: "\"@/\\"
  DatabaseInstance:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Delete
    Properties:
      Engine: mysql
      MultiAZ: true
      DBInstanceClass: !Ref DBInstanceClass
      EngineVersion: 5.7
      StorageType: gp2
      AllocatedStorage: !Ref AllocatedStorage
      MasterUsername: !Sub '{{resolve:secretsmanager:${GeneratedSecretString}::username}}'
      MasterUserPassword: !Sub '{{resolve:secretsmanager:${GeneratedSecretString}::password}}'
  ReadReplicaDatabaseInstance:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Delete
    Properties:
      SourceDBInstanceIdentifier: !Ref DatabaseInstance
      Engine: mysql
      MultiAZ: true
      DBInstanceClass: !Ref DBInstanceClass
      EngineVersion: 5.7
      StorageType: gp2
      AllocatedStorage: !Ref AllocatedStorage
      MasterUsername: !Sub '{{resolve:secretsmanager:${GeneratedSecretString}::username}}'
      MasterUserPassword: !Sub '{{resolve:secretsmanager:${GeneratedSecretString}::password}}'
  CPUUtilizationAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription:  Database CPUUtilization is more than 50%
      Namespace: AWS/RDS
      MetricName: CPUUtilization
      Unit: Percent
      Statistic: Average
      Period: 60
      EvaluationPeriods: 1
      Threshold: 50
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: DBInstanceIdentifier
          Value: !Ref "DatabaseInstance"
