#
# Copyright 2021 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this
# software and associated documentation files (the "Software"), to deal in the Software
# without restriction, including without limitation the rights to use, copy, modify,
# merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
# PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
---
AWSTemplateFormatVersion: 2010-09-09
Description: Test stack for REST API GW
Outputs:
  RestApiGwUsagePlanId:
    Description: Usage Plan Id
    Value:
      Ref: UsagePlan
  RestApiGwId:
    Description: The ID of the REST API Gateway
    Value: !Ref ApplicationsApi
  ApiName:
    Description: Export ApiName dimension
    Value: !Join ["-", ["RestApiGateway-Digito", !Ref "AWS::Region", !Ref "AWS::AccountId", !Select [0, !Split ["-", !Select [2, !Split ["/", !Ref "AWS::StackId"]]]]]]
  RestApiGwStageName:
    Description: The stage name of the REST API Gateway
    Value: !Ref ApplicationsApiStage
  RestApiGwDeploymentId:
    Description: The deployment ID of the REST API Gateway
    Value: !Ref ApplicationsApiDeployment
  RestApiGwStageUrl:
    Description: The URL of the REST API Gateway
    Value: !Sub "https://${ApplicationsApi}.execute-api.${AWS::Region}.amazonaws.com/${ApplicationsApiStage}/app"
  RestApiGwStagePath:
    Description: The Path of the REST API Stage
    Value: !Sub "/${ApplicationsApiStage}/app"
  RestApiGwHost:
    Description: The Host of the REST API Gateway
    Value: !Sub "${ApplicationsApi}.execute-api.${AWS::Region}.amazonaws.com"
  4XXErrorAlarmName:
    Description: REST API GW Alarm based on HTTP4xx metric
    Value: !Ref 4XXErrorAlarm
  AlwaysOKAlarmName:
    Description: Dummy alarm, used in Cucumber tests
    Value: !Ref AlwaysOKAlarm
  ApiKeyId:
    Description: The ID of API key
    Value: !Ref ApiKey
  RestApiGwResourceId:
    Description: The ID of REST API Gateway resource
    Value: !Ref ApiGatewayResource
Parameters:
  RestApiGwQuotaLimit:
    Description: Usage Plan limit value
    Type: String
    Default: 50000
  RestApiGwQuotaPeriod:
    Description: Usage Plan limit value
    Type: String
    Default: WEEK

Resources:
  UsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    Properties:
      ApiStages:
        - ApiId: !Ref ApplicationsApi
          Stage: !Ref ApplicationsApiStage
          Throttle:
            "*/*":
              BurstLimit: 80
              RateLimit: 80
      Description: Test Usage Plan
      Quota:
        Limit: !Ref RestApiGwQuotaLimit
        Offset: 0
        Period: !Ref RestApiGwQuotaPeriod
      Throttle:
        BurstLimit: 100
        RateLimit: 100
      UsagePlanName: !Join
        - "-"
        - - "RestApiGateway-UsagePlan-Digito"
          - !Ref "AWS::Region"
          - !Ref "AWS::AccountId"
          - !Select
            - 0
            - !Split
              - "-"
              - !Select
                - 2
                - !Split
                  - "/"
                  - !Ref "AWS::StackId"

  ApplicationsApiStage:
    DependsOn: ApiAccount
    Type: AWS::ApiGateway::Stage
    Properties:
      TracingEnabled: true
      RestApiId: !Ref ApplicationsApi
      StageName: !Join
        - "-"
        - - "RestApiGateway-Stage-Digito"
          - !Ref "AWS::Region"
          - !Ref "AWS::AccountId"
          - !Select
            - 0
            - !Split
              - "-"
              - !Select
                - 2
                - !Split
                  - "/"
                  - !Ref "AWS::StackId"
      DeploymentId: !Ref ApplicationsApiDeployment
      MethodSettings:
        - LoggingLevel: INFO
          ResourcePath: "/*"
          HttpMethod: "*"
          MetricsEnabled: true
          ThrottlingRateLimit: 250
          ThrottlingBurstLimit: 500

  ApplicationsApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Join
        - "-"
        - - "RestApiGateway-Digito"
          - !Ref "AWS::Region"
          - !Ref "AWS::AccountId"
          - !Select
            - 0
            - !Split
              - "-"
              - !Select
                - 2
                - !Split
                  - "/"
                  - !Ref "AWS::StackId"
      Description: Test API
      ApiKeySourceType: HEADER
      Policy: !Sub |
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Principal": {
                  "AWS": "${AWS::AccountId}"
              },
              "Action": "execute-api:Invoke",
              "Resource": "execute-api:/*"
            }
          ]
        }

  ApiGatewayResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt ApplicationsApi.RootResourceId
      PathPart: 'app'
      RestApiId: !Ref ApplicationsApi

  ApiGatewayModel:
    Type: AWS::ApiGateway::Model
    Properties:
      ContentType: 'application/json'
      RestApiId: !Ref ApplicationsApi
      Schema: { }

  ApiGatewayMethodGet:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: GET
      ResourceId: !Ref ApiGatewayResource
      RestApiId: !Ref ApplicationsApi
      ApiKeyRequired: True
      AuthorizationType: AWS_IAM
      Integration:
        Type: MOCK
        IntegrationResponses:
          - ResponseTemplates:
              application/json: '{"message": "OK"}'
            SelectionPattern: '2\d{2}'
            StatusCode: '200'
        PassthroughBehavior: WHEN_NO_TEMPLATES
        RequestTemplates:
          application/json: '{"statusCode": 200}'
      MethodResponses:
        - ResponseModels:
            application/json: !Ref ApiGatewayModel
          StatusCode: '200'

  ApiGatewayMethodPost:
    Type: AWS::ApiGateway::Method
    DependsOn:
      - LambdaFunction
    Properties:
      HttpMethod: POST
      ResourceId: !Ref ApiGatewayResource
      RestApiId: !Ref ApplicationsApi
      ApiKeyRequired: True
      AuthorizationType: AWS_IAM
      RequestParameters:
        method.request.querystring.params: true
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub "arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaFunction.Arn}/invocations"

  ApiGatewayPushToCloudWatchRole:
    Type: AWS::IAM::Role
    Properties:
      Description: 'Push logs to CloudWatch logs from API Gateway'
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "apigateway.amazonaws.com"
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs"

  ApiAccount:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn: !Sub ${ApiGatewayPushToCloudWatchRole.Arn}

  ApplicationsApiDeployment:
    DependsOn: 
      - ApiGatewayMethodPost
      - ApiGatewayMethodGet
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId: !Ref ApplicationsApi

  ApiKey:
    Type: AWS::ApiGateway::ApiKey
    Properties:
      Description: 'Test API Key'
      Enabled: True
      StageKeys:
        - RestApiId: !Ref ApplicationsApi
          StageName: !Ref ApplicationsApiStage

  UsagePlanKey:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties:
      KeyId: !Ref ApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref UsagePlan

  4XXErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: false
      AlarmDescription: 'Api 4xx Errors'
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: ApiName
          Value: !Join
            - "-"
            - - "RestApiGateway-Digito"
              - !Ref "AWS::Region"
              - !Ref "AWS::AccountId"
              - !Select
                - 0
                - !Split
                  - "-"
                  - !Select
                    - 2
                    - !Split
                      - "/"
                      - !Ref "AWS::StackId"
        - Name: Stage
          Value: !Ref ApplicationsApiStage
      EvaluationPeriods: 5
      DatapointsToAlarm: 3
      MetricName: 4XXError
      Namespace: AWS/ApiGateway
      Period: 60
      ExtendedStatistic: p80
      Threshold: 0
      TreatMissingData: notBreaching

  AlwaysOKAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: false
      AlarmDescription: 'api-gw:alarm:always_ok:2021-03-24'
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 1
      MetricName: AlwaysOK
      Namespace: AWS/ApiGateway
      Period: 60
      Statistic: Minimum
      Threshold: 100
      TreatMissingData: notBreaching

  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.lambda_handler
      Role: !GetAtt LambdaRole.Arn
      Runtime: python3.8
      Timeout: 60
      ReservedConcurrentExecutions: 1
      Code:
        ZipFile: >
          import json

          def lambda_handler(event, context):
            return {
                'statusCode': 200,
                'headers': {
                    'Content-Type': 'application/json',
                    'Access-Control-Allow-Origin': '*'
                },
                'body': json.dumps({
                    'message': 'Hello from Lambda'
                }),
                'isBase64Encoded': False
            }


  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Description: Lambda Role

  LambdaPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - ApplicationsApi
    Properties:
      FunctionName: !Ref LambdaFunction
      Action: "lambda:InvokeFunction"
      Principal: "apigateway.amazonaws.com"
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApplicationsApi}/*/POST/app"
