#
# Copyright 2021 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this
# software and associated documentation files (the "Software"), to deal in the Software
# without restriction, including without limitation the rights to use, copy, modify,
# merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
# PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
---
AWSTemplateFormatVersion: 2010-09-09
Description: Test stack for REST API GW
Outputs:
  RestApiGwUsagePlanId:
    Description: Usage Plan Id
    Value:
      Ref: UsagePlan
  RestApiGwId:
    Description: The ID of the REST API Gateway
    Value: !Ref ApplicationsApi
  RestApiGwStageName:
    Description: The stage name of the REST API Gateway
    Value: !Ref ApplicationsApiStage
  RestApiGwDeploymentId:
    Description: The deployment ID of the REST API Gateway
    Value: !Ref ApplicationsApiDeployment
  RestApiGwStageUrl:
    Description: The URL of the REST API Gateway
    Value: !Sub "https://${ApplicationsApi}.execute-api.${AWS::Region}.amazonaws.com/${ApplicationsApiStage}/app"
  4XXErrorAlarmName:
    Description: REST API GW Alarm based on HTTP4xx metric
    Value: !Ref 4XXErrorAlarm
  5XXErrorAlarmName:
    Description: REST API GW Alarm based on HTTP5xx metric
    Value: !Ref 5XXErrorAlarm
  ApiKeyId:
    Description: The ID of API key
    Value: !Ref ApiKey
  RestApiGwResourceId:
    Description: The ID of REST API Gateway resource
    Value: !Ref ApiGatewayResource
Parameters:
  RestApiGwQuotaLimit:
    Description: Usage Plan limit value
    Type: String
    Default: 50000
  RestApiGwQuotaPeriod:
    Description: Usage Plan limit value
    Type: String
    Default: WEEK
Resources:
  UsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    Properties:
      ApiStages:
        - ApiId: !Ref ApplicationsApi
          Stage: !Ref ApplicationsApiStage
          Throttle:
            "*/*":
              BurstLimit: 80
              RateLimit: 80
      Description: Test Usage Plan
      Quota:
        Limit: !Ref RestApiGwQuotaLimit
        Offset: 0
        Period: !Ref RestApiGwQuotaPeriod
      Throttle:
        BurstLimit: 100
        RateLimit: 100
      UsagePlanName: !Join
        - "-"
        - - "RestApiGateway-UsagePlan-Digito"
          - !Ref "AWS::Region"
          - !Ref "AWS::AccountId"
          - !Select
            - 0
            - !Split
              - "-"
              - !Select
                - 2
                - !Split
                  - "/"
                  - !Ref "AWS::StackId"

  ApplicationsApiStage:
    DependsOn: ApiAccount
    Type: AWS::ApiGateway::Stage
    Properties:
      TracingEnabled: true
      RestApiId: !Ref ApplicationsApi
      StageName: !Join
        - "-"
        - - "RestApiGateway-Stage-Digito"
          - !Ref "AWS::Region"
          - !Ref "AWS::AccountId"
          - !Select
            - 0
            - !Split
              - "-"
              - !Select
                - 2
                - !Split
                  - "/"
                  - !Ref "AWS::StackId"
      DeploymentId: !Ref ApplicationsApiDeployment
      MethodSettings:
        - LoggingLevel: INFO
          ResourcePath: "/*"
          HttpMethod: "*"
          MetricsEnabled: true
          ThrottlingRateLimit: 250
          ThrottlingBurstLimit: 500

  ApplicationsApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Join
        - "-"
        - - "RestApiGateway-Digito"
          - !Ref "AWS::Region"
          - !Ref "AWS::AccountId"
          - !Select
            - 0
            - !Split
              - "-"
              - !Select
                - 2
                - !Split
                  - "/"
                  - !Ref "AWS::StackId"
      Description: Test API
      ApiKeySourceType: HEADER

  ApiGatewayResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt ApplicationsApi.RootResourceId
      PathPart: 'app'
      RestApiId: !Ref ApplicationsApi

  ApiGatewayModel:
    Type: AWS::ApiGateway::Model
    Properties:
      ContentType: 'application/json'
      RestApiId: !Ref ApplicationsApi
      Schema: { }

  ApiGatewayMethodGet:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: GET
      ResourceId: !Ref ApiGatewayResource
      RestApiId:
        !Ref ApplicationsApi
      OperationName: 'app'
      ApiKeyRequired: True
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        IntegrationResponses:
          - ResponseTemplates:
              application/json: '{"message": "OK"}'
            SelectionPattern: '2\d{2}'
            StatusCode: '200'
        PassthroughBehavior: WHEN_NO_TEMPLATES
        RequestTemplates:
          application/json: '{"statusCode": 200}'
      MethodResponses:
        - ResponseModels:
            application/json: !Ref ApiGatewayModel
          StatusCode: '200'

  ApiGatewayPushToCloudWatchRole:
    Type: AWS::IAM::Role
    Properties:
      Description: 'Push logs to CloudWatch logs from API Gateway'
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "apigateway.amazonaws.com"
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs"

  ApiAccount:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn: !Sub ${ApiGatewayPushToCloudWatchRole.Arn}

  ApplicationsApiDeployment:
    DependsOn: ApiGatewayMethodGet
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId: !Ref ApplicationsApi

  ApiKey:
    Type: AWS::ApiGateway::ApiKey
    Properties:
      Description: 'Test API Key'
      Enabled: True
      StageKeys:
        - RestApiId: !Ref ApplicationsApi
          StageName: !Ref ApplicationsApiStage

  UsagePlanKey:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties:
      KeyId: !Ref ApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref UsagePlan

  4XXErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: false
      AlarmDescription: 'Api 4xx Errors'
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: ApiName
          Value: !Join
            - "-"
            - - "RestApiGateway-Digito"
              - !Ref "AWS::Region"
              - !Ref "AWS::AccountId"
              - !Select
                - 0
                - !Split
                  - "-"
                  - !Select
                    - 2
                    - !Split
                      - "/"
                      - !Ref "AWS::StackId"
        - Name: Stage
          Value: !Ref ApplicationsApiStage
      EvaluationPeriods: 5
      DatapointsToAlarm: 3
      MetricName: 4XXError
      Namespace: AWS/ApiGateway
      Period: 60
      ExtendedStatistic: p20
      Threshold: 0
      TreatMissingData: notBreaching

  5XXErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: false
      AlarmDescription: 'Api 5xx Errors'
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: ApiName
          Value: !Join
            - "-"
            - - "RestApiGateway-Digito"
              - !Ref "AWS::Region"
              - !Ref "AWS::AccountId"
              - !Select
                - 0
                - !Split
                  - "-"
                  - !Select
                    - 2
                    - !Split
                      - "/"
                      - !Ref "AWS::StackId"
        - Name: Stage
          Value: !Ref ApplicationsApiStage
      EvaluationPeriods: 5
      DatapointsToAlarm: 3
      MetricName: 5XXError
      Namespace: AWS/ApiGateway
      Period: 60
      ExtendedStatistic: p10
      Threshold: 0
      TreatMissingData: notBreaching