#
# Copyright 2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this
# software and associated documentation files (the "Software"), to deal in the Software
# without restriction, including without limitation the rights to use, copy, modify,
# merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
# PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
---
AWSTemplateFormatVersion: 2010-09-09
Description: Test stack for S3 and related resources. Contains all alarms
Outputs:
  S3BackupBucketName:
    Description: S3 backup bucket name
    Value: !Ref S3BackupBucket
  S3BucketForReplicationName:
    Description: S3BucketForReplication bucket name
    Value: !Ref S3BucketForReplication
  S3BucketToRestoreName:
    Description: S3 bucket name to restore
    Value: !Ref S3BucketToRestore
  Health5xxErrorsCountAlarmName:
    Description: Alarm
    Value: !Ref  S3Health5xxErrorsCountAlarm
  TotalRequestLatencyAlarmName:
    Description: Alarm
    Value: !Ref  S3TotalRequestLatencyAlarm
  ReplicationLatencyAlarmName:
    Description: Alarm
    Value: !Ref  S3ReplicationLatencyAlarm
  SNSTopicName:
    Description: SNS Topic Name
    Value: !Ref SNSTopic
  RoleApproveCleanBucketArn:
    Description: ARN of RoleApproveCleanBucket
    Value: !GetAtt RoleApproveCleanBucket.Arn
Parameters:
  CleanupS3BucketLambdaArn:
     Description: ARN of Cleanup S3 Bucket Lambda Function
     Type: String
Resources:
  S3BackupBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      BucketName: !Join
        - "-"
        - - "s3-backup-bucket-digito"
          - !Ref "AWS::Region"
          - !Ref "AWS::AccountId"
          - !Select
            - 0
            - !Split
              - "-"
              - !Select
                - 2
                - !Split
                  - "/"
                  - !Ref "AWS::StackId"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
  S3BucketForReplication:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      BucketName: !Join
        - "-"
        - - "s3-replication-bucket-digito"
          - !Ref "AWS::Region"
          - !Ref "AWS::AccountId"
          - !Select
            - 0
            - !Split
              - "-"
              - !Select
                - 2
                - !Split
                  - "/"
                  - !Ref "AWS::StackId"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
  S3BucketToRestore:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      BucketName: !Join
        - "-"
        - - "s3-restore-bucket-digito"
          - !Select
            - 0
            - !Split
              - "-"
              - !Select
                - 2
                - !Split
                  - "/"
                  - !Ref "AWS::StackId"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      MetricsConfigurations:
        - Id: !Join
            - "-"
            - - "s3-restore-bucket-digito"
              - !Select
                - 0
                - !Split
                  - "-"
                  - !Select
                    - 2
                    - !Split
                      - "/"
                      - !Ref "AWS::StackId"
              - "metrics"
      ReplicationConfiguration:
        Role: !GetAtt S3BucketReplicationRole.Arn
        Rules:
          - Status: Enabled
            Filter:
              Prefix: ''
            DeleteMarkerReplication:
              Status: Enabled
            Destination:
              Bucket: !GetAtt S3BucketForReplication.Arn
              Metrics:
                Status: Enabled
                EventThreshold:
                  Minutes: 15
              ReplicationTime:
                Status: Enabled
                Time:
                  Minutes: 15
            Priority: 1
  S3BucketReplicationRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service:
                - s3.amazonaws.com
  S3BucketReplicationPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - 's3:GetReplicationConfiguration'
              - 's3:ListBucket'
            Effect: Allow
            Resource: !GetAtt S3BucketToRestore.Arn
          - Action:
              - 's3:GetObjectVersion'
              - 's3:GetObjectVersionAcl'
              - 's3:GetObjectVersionTagging'
            Effect: Allow
            Resource:
              - !Join
                - ''
                - - !GetAtt S3BucketToRestore.Arn
                  - /*
          - Action:
              - 's3:ReplicateObject'
              - 's3:ReplicateDelete'
              - 's3:ReplicateTags'
            Effect: Allow
            Resource:
              - !Join
                - ''
                - - !GetAtt S3BucketForReplication.Arn
                  - /*
      PolicyName: S3BucketReplicationPolicy
      Roles:
        - !Ref S3BucketReplicationRole
  KmsKey:
    Type: AWS::KMS::Key
    Properties:
      KeyPolicy:
        Version: '2012-10-17'
        Id: !Join
          - "-"
          - - "kms-key-policy"
            - !Select
              - 0
              - !Split
                - "-"
                - !Select
                  - 2
                  - !Split
                    - "/"
                    - !Ref "AWS::StackId"
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: kms:*
            Resource: "*"
  SNSTopic:
    Type: "AWS::SNS::Topic"
    Properties:
      KmsMasterKeyId: !Ref KmsKey
  SNSTopicPolicy:
    Type: "AWS::SNS::TopicPolicy"
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Id: SNSTopicPolicy
        Statement:
          - Sid: SNSTopicPolicyStatement
            Effect: Allow
            Principal:
              Service:
                - cloudwatch.amazonaws.com
            Action:
              - SNS:Publish
            Resource: !Ref SNSTopic
            Condition:
              StringEquals:
                AWS:SourceAccount: !Ref "AWS::AccountId"
      Topics:
        - !Ref SNSTopic
  RoleApproveCleanBucket:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Ref "AWS::AccountId"
            Action:
              - sts:AssumeRole
  PolicyApproveCleanBucket:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: DigitoRestoreFromBackupAssumePolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Resource: "*"
            Action:
              - ssm:SendAutomationSignal
      Roles:
        - Ref: RoleApproveCleanBucket
  S3Health5xxErrorsCountAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmDescription: "s3:alarm:health-5xxErrors_count:2020-04-01"
      ActionsEnabled: false
      MetricName: 5xxErrors
      Namespace: AWS/S3
      Statistic: Sum
      Dimensions:
        - Name: BucketName
          Value: !Ref S3BucketToRestore
      Period: 60
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Threshold: 0
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      Unit: Count
  S3TotalRequestLatencyAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmDescription: "s3:alarm:health-total_tequest_latency:2020-04-01"
      ActionsEnabled: false
      MetricName: TotalRequestLatency
      Namespace: AWS/S3
      Statistic: Sum
      Dimensions:
        - Name: BucketName
          Value: !Ref S3BucketToRestore
      Period: 60
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Threshold: 60
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: missing
      Unit: Milliseconds
  S3ReplicationLatencyAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmDescription: "s3:alarm:recovery-replication_latency:2020-04-01"
      ActionsEnabled: false
      MetricName: ReplicationLatency
      Namespace: AWS/S3
      Statistic: Maximum
      Dimensions:
        - Name: BucketName
          Value: !Ref S3BucketToRestore
      Period: 60
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Threshold: 60
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: ignore
      Unit: Seconds

  # To clean S3 buckets before deleting stack.
  CleanupS3BucketsOnDelete:
    Type: Custom::CleanupS3BucketsOnDelete
    Properties:
      ServiceToken: !Ref CleanupS3BucketLambdaArn
      BucketNames:
        - !Ref S3BackupBucket
        - !Ref S3BucketForReplication
        - !Ref S3BucketToRestore
