#
# Copyright 2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this
# software and associated documentation files (the "Software"), to deal in the Software
# without restriction, including without limitation the rights to use, copy, modify,
# merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
# PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
---
AWSTemplateFormatVersion: 2010-09-09
Description: Test stack for S3 and related resources. Contains all alarms
Outputs:
  S3BackupBucketName:
    Description: S3 backup bucket name
    Value: !Ref S3BackupBucket
  S3BucketToRestoreName:
    Description: S3 bucket name to restore
    Value: !Ref S3BucketToRestore
  Health4xxErrorsCountAlarmName:
    Description: Alarm
    Value: !Ref  S3Health4xxErrorsCountAlarm
  Health5xxErrorsCountAlarmName:
    Description: Alarm
    Value: !Ref  S3Health5xxErrorsCountAlarm
  TotalRequestLatencyAlarmName:
    Description: Alarm
    Value: !Ref  S3TotalRequestLatencyAlarm
  ReplicationLatencyAlarmName:
    Description: Alarm
    Value: !Ref  S3ReplicationLatencyAlarm
  SNSTopicName:
    Description: SNS Topic Name
    Value: !Ref SNSTopic
  RoleApproveCleanBucketArn:
    Description: ARN of RoleApproveCleanBucket
    Value: !GetAtt RoleApproveCleanBucket.Arn
Resources:
  S3BackupBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join
        - "-"
        - - "s3-backup-bucket-digito"
          - !Ref "AWS::Region"
          - !Ref "AWS::AccountId"
          - !Select
            - 0
            - !Split
              - "-"
              - !Select
                - 2
                - !Split
                  - "/"
                  - !Ref "AWS::StackId"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
  S3BucketToRestore:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join
        - "-"
        - - "s3-bucket-to-restore-digito"
          - !Ref "AWS::Region"
          - !Ref "AWS::AccountId"
          - !Select
            - 0
            - !Split
              - "-"
              - !Select
                - 2
                - !Split
                  - "/"
                  - !Ref "AWS::StackId"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      MetricsConfigurations:
        -
          Id: "all_objects"
  SNSTopic:
    Type: "AWS::SNS::Topic"
  SNSTopicPolicy:
    Type: "AWS::SNS::TopicPolicy"
    Properties:
      PolicyDocument:
        Version: '2008-10-17'
        Id: SNSTopicPolicy
        Statement:
          - Sid: SNSTopicPolicyStatement
            Effect: Allow
            Principal:
              Service:
                - cloudwatch.amazonaws.com
            Action:
              - SNS:Publish
            Resource: !Ref SNSTopic
            Condition:
              StringEquals:
                AWS:SourceAccount: !Ref "AWS::AccountId"
      Topics:
        - !Ref SNSTopic
  RoleApproveCleanBucket:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Ref "AWS::AccountId"
            Action:
              - sts:AssumeRole
  PolicyApproveCleanBucket:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: DigitoRestoreFromBackupAssumePolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Resource: "*"
            Action:
              - ssm:SendAutomationSignal
      Roles:
        - Ref: RoleApproveCleanBucket
  S3Health4xxErrorsCountAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmDescription: "s3:alarm:health-4xxErrors_count:2020-04-01"
      ActionsEnabled: false
      MetricName: 4xxErrors
      Namespace: AWS/S3
      Statistic: Sum
      Dimensions:
        - Name: BucketName
          Value: !Ref S3BucketToRestore
        - Name: FilterId
          Value: "all_objects"
      Period: 60
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Threshold: 0
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: missing
      Unit: Count
  S3Health5xxErrorsCountAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmDescription: "s3:alarm:health-5xxErrors_count:2020-04-01"
      ActionsEnabled: false
      MetricName: 5xxErrors
      Namespace: AWS/S3
      Statistic: Sum
      Dimensions:
        - Name: BucketName
          Value: !Ref S3BucketToRestore
      Period: 60
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Threshold: 0
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: missing
      Unit: Count
  S3TotalRequestLatencyAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmDescription: "s3:alarm:health-total_tequest_latency:2020-04-01"
      ActionsEnabled: false
      MetricName: TotalRequestLatency
      Namespace: AWS/S3
      Statistic: Sum
      Dimensions:
        - Name: BucketName
          Value: !Ref S3BucketToRestore
      Period: 60
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Threshold: 60
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: missing
      Unit: Milliseconds
  S3ReplicationLatencyAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmDescription: "s3:alarm:recovery-replication_latency:2020-04-01"
      ActionsEnabled: false
      MetricName: ReplicationLatency
      Namespace: AWS/S3
      Statistic: Maximum
      Dimensions:
        - Name: BucketName
          Value: !Ref S3BucketToRestore
      Period: 60
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Threshold: 60
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: ignore
      Unit: Seconds