AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  FunctionName:
    Type: String
    Default: '${FunctionName}'
  SNSTopicARN:
    Type: String
  Threshold:
    Type: Number
    Default: ${Threshold}
Resources:
  ThrottlesAlarm:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmActions:
        - Ref: SNSTopicARN
      AlarmDescription:
        Fn::Join: [ '', [ 'Alarm by Digito that reports when sustained throttles occur' ] ]
      AlarmName:
        Fn::Join: [ '', [ 'DigitoLambdaThrottles-', Ref: FunctionName ] ]
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 3
      DatapointsToAlarm: 3
      Dimensions:
        - Name: FunctionName
          Value:
            Ref: FunctionName
      MetricName: Throttles
      Namespace: AWS/Lambda
      Period: 60
      Statistic: Maximum
      Threshold:
        Ref: Threshold
      TreatMissingData: missing
    Metadata:
      'AWS::Digito::Monitoring':
        recommendationId: 'stateless-compute:alarm:lambda-throttles:2020-07-13'
