---
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SNSTopicARN:
    Type: String
Resources:
  ${AlarmLogicalId}:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmName: ${AlarmName}
      AlarmDescription: "Alarm by Digito that reports when network load balancer unhealthy host count is greater than or equal to a threshold"
      AlarmActions:
        - Ref: SNSTopicARN
      MetricName: UnHealthyHostCount
      Namespace: AWS/NetworkELB
      Dimensions:
        - Name: LoadBalancer
          Value: ${NetworkELBName}
        - Name: TargetGroup
          Value: ${TargetGroup}
      Period: 60
      Statistic: Sum
      Threshold: ${Threshold}
      EvaluationPeriods: 5
      DatapointsToAlarm: 3
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: notBreaching
      Unit: Count
