AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SNSTopicARN:
    Type: String
Resources:
  ${AlarmLogicalId}:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmActions:
        - Ref: SNSTopicARN
      AlarmDescription:
        Fn::Join: [ '', [ 'Alarm by Digito that reports when a number of TotalRequestLatency is over ', ${Threshold}, 'milliseconds' ] ]
      AlarmName: ${AlarmName}
      MetricName: TotalRequestLatency
      Namespace: AWS/S3
      Statistic: Maximum
      Dimensions:
        - Name: BucketName
          Value: '${S3BucketName}'
        - Name: FilterId
          Value: "${S3BucketName}-metrics"
      Period: 60
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Threshold: ${Threshold}
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: missing
      Unit: Milliseconds
