AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SNSTopicARN:
    Type: String
Resources:
  ${AlarmLogicalId}:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions:
        - Ref: SNSTopicARN
      AlarmDescription:
        Fn::Join: [ '', [ 'Alarm by Digito that reports when memory utilization is anomalous with band width ', ${Threshold}] ]
      AlarmName: ${AlarmName}
      ComparisonOperator: LessThanLowerOrGreaterThanUpperThreshold
      EvaluationPeriods: 3
      DatapointsToAlarm: 3
      ThresholdMetricId: ad1
      TreatMissingData: missing
      Metrics:
        - Id: ad1
          Expression:
            Fn::Join: [ '', [ 'ANOMALY_DETECTION_BAND(m1,', ${Threshold}, ')' ] ]
        - Id: m1
          MetricStat:
            Metric:
              MetricName: mem_used_percent
              Namespace: CWAgent
              Dimensions:
                - Name: InstanceId
                  Value: '${InstanceId}'
            Period: 60
            Stat: Maximum
            Unit: Percent
