---
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SNSTopicARN:
    Type: String
Resources:
  ${AlarmLogicalId}:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmName: ${AlarmName}
      AlarmDescription:
        Fn::Sub: 'Alarm by Digito that reports when NumberOfMessagesSent deviation is over ${Threshold}%'
      AlarmActions:
        - Ref: SNSTopicARN
      Metrics:
        - Expression:
            Fn::Sub: "ANOMALY_DETECTION_BAND(m1,${Threshold})"
          Id: ad1
        - Id: m1
          MetricStat:
            Metric:
              MetricName: NumberOfMessagesSent
              Namespace: AWS/SQS
              Dimensions:
                - Name: QueueName
                  Value: ${QueueName}
            Period: 300
            Stat: Average
      EvaluationPeriods: 5
      DatapointsToAlarm: 3
      ThresholdMetricId: ad1
      ComparisonOperator: LessThanLowerOrGreaterThanUpperThreshold
      TreatMissingData: missing
