AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SNSTopicARN:
    Type: String
Resources:
  ${AlarmLogicalId}:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmActions:
        - Ref: SNSTopicARN
      AlarmDescription: 'Alarm by Digito for Kinesis Data Analytics for SQL, that indicates how far behind from the current time an application is reading from the streaming source'
      AlarmName: ${AlarmName}
      ComparisonOperator: LessThanLowerOrGreaterThanUpperThreshold
      EvaluationPeriods: ${EvaluationPeriods}
      DatapointsToAlarm: ${DatapointsToAlarm}
      Metrics:
        - Expression:
             'ANOMALY_DETECTION_BAND(m1,${Threshold})'
          Id: ad1
        - Id: m1
          MetricStat:
            Metric:
              MetricName: MillisBehindLatest
              Namespace: AWS/KinesisAnalytics
              Dimensions:
                - Name: Application
                  Value: '${KinesisAnalyticsAppName}'
                - Name: Id
                  Value: '${KinesisAnalyticsInputId}'
                - Name: Flow
                  Value: Input
            Period: 60
            Stat: Maximum
      ThresholdMetricId: ad1
      TreatMissingData: missing
