AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SNSTopicARN:
    Type: String
Resources:
  ${AlarmLogicalId}:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmName: ${AlarmName}
      AlarmDescription: "Alarm by Digito that reports when count of http 5xx responses received by load balancer is greater than or equal to a threshold"
      AlarmActions:
        - Ref: SNSTopicARN
      MetricName: HTTPCode_ELB_5XX_Count
      Namespace: AWS/ApplicationELB
      Dimensions:
        - Name: LoadBalancer
          Value: ${ApplicationELBArn}
      Period: 60
      Statistic: Maximum
      Threshold: ${Threshold}
      EvaluationPeriods: ${MaxTimeMinutes}
      DatapointsToAlarm: ${MaxTimeMinutes}
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: notBreaching
      Unit: Count
