AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SNSTopicARN:
    Type: String
Resources:
  ${AlarmLogicalId}:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmActions:
        - Ref: SNSTopicARN
      AlarmDescription:
        Fn::Join: [ '', [ 'Alarm by Digito that reports when sustained errors occur' ] ]
      AlarmName: ${AlarmName}
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 3
      DatapointsToAlarm: 3
      Dimensions:
        - Name: FunctionName
          Value: '${FunctionName}'
      MetricName: Errors
      Namespace: AWS/Lambda
      Period: 60
      Statistic: Maximum
      Threshold: ${Threshold}
      TreatMissingData: missing
