---
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SNSTopicARN:
    Type: String
Resources:
  ${AlarmLogicalId}:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmName: ${AlarmName}
      AlarmDescription:
        Fn::Sub: 'Alarm by Digito that reports when VolumeWriteIOPs deviation is over ${Threshold}%'
      AlarmActions:
        - Ref: SNSTopicARN
      Metrics:
        - Expression:
            Fn::Sub: "ANOMALY_DETECTION_BAND(m1,${Threshold})"
          Id: ad1
        - Id: m1
          MetricStat:
            Metric:
              MetricName: VolumeWriteIOPs
              Namespace: AWS/DocDB
              Dimensions:
                - Name: DBClusterIdentifier
                  Value: ${DBClusterIdentifier}
            Period: 300
            Stat: Maximum
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      ThresholdMetricId: ad1
      ComparisonOperator: GreaterThanUpperThreshold
      TreatMissingData: missing
