---
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SNSTopicARN:
    Type: String
Resources:
  ${AlarmLogicalId}:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmName: ${AlarmName}
      AlarmDescription: "Alarm by Digito for Amazon Redshift, that reports number of seconds used by concurrency scaling clusters that have active query processing activity, is equal to or greater than the specified ${Threshold}."
      AlarmActions:
        - Ref: SNSTopicARN
      MetricName: ConcurrencyScalingSeconds
      Namespace: AWS/Redshift
      Dimensions:
        - Name: ClusterIdentifier
          Value: ${ClusterName}
      Period: 86400
      Statistic: Sum
      Threshold: ${Threshold}
      EvaluationPeriods: ${EvaluationPeriods}
      DatapointsToAlarm: ${DatapointsToAlarm}
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: missing
