---
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SNSTopicARN:
    Type: String
Resources:
  ${AlarmLogicalId}:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmName: ${AlarmName}
      AlarmDescription: "Alarm by Digito for Amazon Redshift, that reports disk space used at the cluster level, is equal to or greater than the specified ${Threshold}."
      AlarmActions:
        - Ref: SNSTopicARN
      MetricName: PercentageDiskSpaceUsed
      Namespace: AWS/Redshift
      Dimensions:
        - Name: ClusterIdentifier
          Value: '${ClusterName}'
      Period: 60
      Statistic: Maximum
      Threshold: ${Threshold}
      EvaluationPeriods: ${EvaluationPeriods}
      DatapointsToAlarm: ${DatapointsToAlarm}
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: missing
