AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  DBInstanceIdentifier:
    Type: String
    Default: '${DBInstanceIdentifier}'
  SNSTopicARN:
    Type: String
  Threshold:
    Type: Number
    Default: ${Threshold}
Resources:
  LowStorageAlarm:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmActions:
        - Ref: SNSTopicARN
      AlarmDescription:
        Fn::Join: [ '', [ 'Alarm by Digito that reports when free storage is under ', Ref: Threshold, 'GB' ] ]
      AlarmName:
        Fn::Join: [ '', [ 'DigitoRdsLowStorage-', Ref: DBInstanceIdentifier ] ]
      ComparisonOperator: LessThanOrEqualToThreshold
      DatapointsToAlarm: 3
      Dimensions:
        - Name: DBInstanceIdentifier
          Value:
            Ref: DBInstanceIdentifier
      EvaluationPeriods: 5
      MetricName: FreeStorageSpace
      Namespace: AWS/RDS
      Period: 60
      Statistic: Minimum
      Threshold:
        Ref: Threshold
      TreatMissingData: missing
