---
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SNSTopicARN:
    Type: String
Resources:
  ${AlarmLogicalId}:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmName: ${AlarmName}
      AlarmDescription: "Alarm by Digito that reports when count of lambda user errors received by load balancer from lambda targets is greater than or equal to a threshold"
      AlarmActions:
        - Ref: SNSTopicARN
      MetricName: LambdaUserError
      Namespace: AWS/ApplicationELB
      Dimensions:
        - Name: TargetGroup
          Value: ${LambdaTargetFullName}
      Period: 60
      Statistic: Sum
      Threshold: ${Threshold}
      EvaluationPeriods: ${EvaluationPeriods}
      DatapointsToAlarm: ${DatapointsToAlarm}
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: notBreaching
      Unit: Count
