AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SNSTopicARN:
    Type: String
Resources:
  ${AlarmLogicalId}:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmDescription: 'Alarm by Digito that reports when amount of conditional check failed requests is greater than or equal to threshold ${Threshold}'
      AlarmName: ${AlarmName}
      AlarmActions:
        - Ref: SNSTopicARN
      MetricName: ConditionalCheckFailedRequests
      Namespace: AWS/DynamoDB
      Statistic: Sum
      Dimensions:
        - Name: TableName
          Value: ${DynamoDbTable}
      Period: 60
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Threshold: ${Threshold}
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: notBreaching
      Unit: Count
    Metadata:
      'AWS::Digito::Monitoring':
        recommendationId: 'dynamodb:alarm:health_conditional_check_failed_requests:2020-04-01'
