AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SNSTopicARN:
    Type: String
Resources:
  ${AlarmLogicalId}:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmActions:
        - Ref: SNSTopicARN
      AlarmDescription: 'Alarm by Digito for Kinesis Data Analytics for SQL applications that reports deviations with regards to time taken for each Lambda function invocation, which is exceeding specified ${Threshold} range'
      AlarmName: ${AlarmName}
      ComparisonOperator: LessThanLowerOrGreaterThanUpperThreshold
      EvaluationPeriods: ${EvaluationPeriods}
      DatapointsToAlarm: ${DatapointsToAlarm}
      Metrics:
        - Expression:
             'ANOMALY_DETECTION_BAND(m1,${Threshold})'
          Id: ad1
        - Id: m1
          MetricStat:
            Metric:
              MetricName: LambdaDelivery.Duration
              Namespace: AWS/KinesisAnalytics
              Dimensions:
                - Name: Application
                  Value: '${KinesisAnalyticsAppName}'
                - Name: Id
                  Value: '${KinesisAnalyticsOutputId}'
                - Name: Flow
                  Value: Output
            Period: 60
            Stat: Maximum
      ThresholdMetricId: ad1
      TreatMissingData: missing
