---
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SNSTopicARN:
    Type: String
Outputs:
  AlarmName:
    Description: Percent IO Limit Alarm Name
    Value: !Ref ${AlarmLogicalId}
Resources:
  ${AlarmLogicalId}:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmName: ${AlarmName}
      AlarmDescription: "Alarm by Digito that reports when EFS I/O load is more than 90% for too much time"
      ActionsEnabled: false
      MetricName: PercentIOLimit
      Namespace: AWS/EFS
      Dimensions:
        - Name: FileSystemId
          Value: ${FileSystem}
      Period: 60
      Statistic: Average
      Threshold: ${Threshold}
      EvaluationPeriods: ${MaxTimeMinutes}
      DatapointsToAlarm: ${MaxTimeMinutes}
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: missing
