---
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SNSTopicARN:
    Type: String
Resources:
  ${AlarmLogicalId}:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmName: ${AlarmName}
      AlarmDescription: |
        Alarm by Digito that can be occurred if the age of the oldest message is much higher than the AverageDurationToProcessSentMessage.
        It notices that messages are not being processed quickly enough.
      ActionsEnabled: false
      AlarmActions:
        - Ref: SNSTopicARN
      MetricName: ApproximateAgeOfOldestMessage
      Namespace: AWS/SQS
      Dimensions:
        - Name: QueueName
          Value: ${QueueName}
      Period: 60
      Statistic: Maximum
      Threshold: ${Threshold}
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
