AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SNSTopicARN:
    Type: String
Resources:
  ${AlarmLogicalId}:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmActions:
        - Ref: SNSTopicARN
      AlarmDescription: 'Alarm by Digito that reports when average memory growth is anomalous with deviation ${Threshold}'
      AlarmName: ${AlarmName}
      ComparisonOperator: LessThanLowerOrGreaterThanUpperThreshold
      EvaluationPeriods: 5
      DatapointsToAlarm: 3
      Metrics:
        - Expression:
             'ANOMALY_DETECTION_BAND(m1,${Threshold})'
          Id: ad1
        - Id: m1
          MetricStat:
            Metric:
              MetricName: memory_utilization
              Namespace: LambdaInsights
              Dimensions:
                - Name: function_name
                  Value: '${FunctionName}'
            Period: 180
            Stat: Average
      ThresholdMetricId: ad1
      TreatMissingData: missing
