AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SNSTopicARN:
    Type: String
Resources:
  BurstBalance:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmActions:
        - Ref: SNSTopicARN
      AlarmDescription:
        Fn::Join: [ '', [ 'Alarm by Digito that reports when drained burst balance is below ', ${Threshold} ] ]
      AlarmName: ${AlarmName}
      ComparisonOperator: LessThanThreshold
      EvaluationPeriods: 3
      DatapointsToAlarm: 1
      Dimensions:
        - Name: VolumeId
          Value: '${VolumeId}'
      MetricName: BurstBalance
      Namespace: AWS/EC2
      Period: 300
      Statistic: Average
      Threshold: ${Threshold}
      TreatMissingData: missing
    Metadata:
      'AWS::Digito::Monitoring':
        recommendationId: 'ebs:alarm:ebs-burst-balance:2020-12-06'
