---
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SNSTopicARN:
    Type: String
Resources:
  ${AlarmLogicalId}:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmActions:
          - Ref: SNSTopicARN
      AlarmDescription: 'Digito alarm for Athena that indicates if the query execution has failed, is exceeding specified ${Threshold} limit'
      AlarmName: ${AlarmName}
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: ${EvaluationPeriods}
      DatapointsToAlarm: ${DatapointsToAlarm}
      Dimensions:
        - Name: WorkGroup
          Value: '${AthenaWorkGroupName}'
        - Name: QueryState
          Value: FAILED
        - Name: QueryType
          Value: DML
      Namespace: AWS/Athena
      MetricName: TotalExecutionTime
      Period: 60
      Statistic: SampleCount
      Threshold: ${Threshold}
      TreatMissingData: missing