AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SNSTopicARN:
    Type: String
Resources:
  ${AlarmLogicalId}:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmActions:
        - Ref: SNSTopicARN
      AlarmDescription: 'Health alarm by Digito that reports when the time taken per GetRecords operation is over ${Threshold} milliseconds'
      AlarmName: ${AlarmName}
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: StreamName
          Value: '${KinesisDataStreamName}'
      DatapointsToAlarm: ${DatapointsToAlarm}
      EvaluationPeriods: ${EvaluationPeriods}
      MetricName: WriteProvisionedThroughputExceeded
      Namespace: AWS/Kinesis
      Period: 60
      Statistic: Maximum
      Threshold: ${Threshold}
      TreatMissingData: missing
