---
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SNSTopicARN:
    Type: String
Resources:
  ${AlarmLogicalId}:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmName: ${AlarmName}
      AlarmDescription:
        Fn::Sub: 'Alarm by Digito that reports when CPUCreditBalance is lower or equal to ${Threshold}'
      MetricName: CPUCreditBalance
      Namespace: AWS/DocDB
      Dimensions:
        - Name: DBInstanceIdentifier
          Value: ${DBInstanceIdentifier}
      Period: 60
      Statistic: Minimum
      Threshold: ${Threshold}
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      ComparisonOperator: LessThanOrEqualToThreshold
      TreatMissingData: missing
