AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SNSTopicARN:
    Type: String
Resources:
  ${AlarmLogicalId}:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmDescription: 'Alarm by Digito that reports when amount of read throttle events is greater than ${Threshold}'
      AlarmName: ${AlarmName}
      AlarmActions:
        - Ref: SNSTopicARN
      MetricName: ReadThrottleEvents
      Namespace: AWS/DynamoDB
      Statistic: Sum
      Dimensions:
        - Name: TableName
          Value: ${DynamoDbTable}
      Period: 60
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Threshold: ${Threshold}
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: notBreaching
      Unit: Count
    Metadata:
      'AWS::Digito::Monitoring':
        recommendationId: 'dynamodb:alarm:health-read_throttle_events:2020-04-01'
