AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SNSTopicARN:
    Type: String
Outputs:
  AlarmName:
    Type: String
    Description: Client Connections Alarm Name
    Default: !Ref ClientConnectionsAlarm
Resources:
  ClientConnectionsAnomalyDetector:
    Type: AWS::CloudWatch::AnomalyDetector
    Properties:
      MetricName: ClientConnections
      Namespace: AWS/EFS
      Stat: Average
      Dimensions:
        - Name: EFS
          Value: ${FileSystem}
  ClientConnectionsAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmName: ClientConnections
      AlarmDescription:
        Fn::Join: [ '', [ 'Alarm by Digito that reports when client connections deviation is over ', ${Threshold}] ]
      ActionsEnabled: false
      AlarmActions:
        - Ref: SNSTopicARN
      Metrics:
        - Expression:
          Fn::Join: [ '',["ANOMALY_DETECTION_BAND(m1,",${Threshold}, ")"]]
          Id: ad1
        - Id: m1
          MetricStat:
            Metric:
              MetricName: ClientConnections
              Namespace: AWS/EFS
            Period: 60
            Stat: Average
      EvaluationPeriods: 5
      DatapointsToAlarm: 3
      ThresholdMetricId: ad1
      ComparisonOperator: LessThanLowerOrGreaterThanUpperThreshold
      TreatMissingData: missing
