AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SNSTopicARN:
    Type: String
Resources:
  ${AlarmLogicalId}:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmActions:
        - Ref: SNSTopicARN
      AlarmDescription: 'Digito alarm for Kinesis Data Analytics for SQL applications that tracks if the number of records returned by a Lambda function that were marked with DeliveryFailed status, is exceeding specified ${Threshold} limit'
      AlarmName: ${AlarmName}
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: ${EvaluationPeriods}
      DatapointsToAlarm: ${DatapointsToAlarm}
      Dimensions:
        - Name: Application
          Value: '${KinesisAnalyticsAppName}'
        - Name: Id
          Value: '${KinesisAnalyticsOutputId}'
        - Name: Flow
          Value: Output
      Namespace: AWS/KinesisAnalytics
      MetricName: LambdaDelivery.DeliveryFailedRecords
      Period: 60
      Statistic: Maximum
      Threshold: ${Threshold}
      TreatMissingData: missing
