AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SNSTopicARN:
    Type: String
Resources:
  ${AlarmLogicalId}:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmActions:
        - Ref: SNSTopicARN
      AlarmDescription: 'Alarm by Digito for Elasticache Redis at engine level for hosts having 4 or more VCPUs that indicates when the percentage of CPU utilization has exceeded the specified ${Threshold} limit'
      AlarmName: ${AlarmName}
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 5
      DatapointsToAlarm: 2
      Dimensions:
        - Name: CacheClusterId
          Value: '${ClusterId}'
      MetricName: EngineCPUUtilization
      Namespace: AWS/ElastiCache
      Period: 60
      Statistic: Maximum
      Threshold: ${Threshold}
      TreatMissingData: missing
