#
# Copyright 2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this
# software and associated documentation files (the "Software"), to deal in the Software
# without restriction, including without limitation the rights to use, copy, modify,
# merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
# PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
---
AWSTemplateFormatVersion: 2010-09-09
Description: Role for Digito-CreateElasticacheReplicationGroupFromSnapshotSOP_2020-10-26
Outputs:
  DigitoElasticacheCreateCacheClusterFromSnapshotAssumeRole:
    Description: Digito-CreateElasticacheReplicationGroupFromSnapshotSOP_2020-10-26 Automation Assume Role ARN
    Value: !GetAtt DigitoElasticacheCreateCacheClusterFromSnapshotAssumeRole.Arn
Resources:
  DigitoElasticacheCreateCacheClusterFromSnapshotAssumeRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ssm.amazonaws.com
            Action:
              - sts:AssumeRole
  DigitoElasticacheCreateCacheClusterFromSnapshotAssumePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: DigitoElasticacheCreateCacheClusterFromSnapshotAssumePolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Resource: "*"
            Action:
              - elasticache:CreateReplicationGroup
              - elasticache:DescribeCacheClusters
              - elasticache:DescribeReplicationGroups
              - elasticache:DescribeSnapshots
          - Effect: Allow
            Resource: "*"
            Action:
              - kms:CreateGrant
              - kms:DescribeKey
            Condition:
              StringLike:
                kms:ViaService: # Both services are required. See https://docs.aws.amazon.com/kms/latest/developerguide/policy-conditions.html#conditions-kms-via-service
                  - elasticache.*.amazonaws.com
                  - dax.*.amazonaws.com

      Roles:
        - Ref: DigitoElasticacheCreateCacheClusterFromSnapshotAssumeRole
