---
AWSTemplateFormatVersion: 2010-09-09
Parameters:
  SNSTopicARN:
    Type: String
Resources:
  ${AlarmLogicalId}:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmName: ${AlarmName}
      AlarmActions:
        - Ref: SNSTopicARN
      AlarmDescription: "Alarm by Digito for AWS Backup that indicates AWS Backup made an attempt to initialize a backup job and failed to do so under the ${BackupVaultName} backup vault"
      ActionsEnabled: false
      MetricName: NumberOfBackupJobsFailed
      Namespace: AWS/Backup
      Period: 60
      Statistic: Maximum
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      ComparisonOperator: GreaterThanThreshold
      Threshold: ${Threshold}
      Dimensions:
        - Name: BackupVaultName
          Value: ${BackupVaultName}
      TreatMissingData: notBreaching
...
